
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const ConvoyStatus = {
  DRAFT: 'DRAFT',
  READY: 'READY',
  ACTIVE: 'ACTIVE',
  ARCHIVED: 'ARCHIVED'
} as const

export type ConvoyStatus = (typeof ConvoyStatus)[keyof typeof ConvoyStatus]
