
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ConvoySegment` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model ConvoySegment
 * 
 */
export type ConvoySegmentModel = runtime.Types.Result.DefaultSelection<Prisma.$ConvoySegmentPayload>

export type AggregateConvoySegment = {
  _count: ConvoySegmentCountAggregateOutputType | null
  _avg: ConvoySegmentAvgAggregateOutputType | null
  _sum: ConvoySegmentSumAggregateOutputType | null
  _min: ConvoySegmentMinAggregateOutputType | null
  _max: ConvoySegmentMaxAggregateOutputType | null
}

export type ConvoySegmentAvgAggregateOutputType = {
  order: number | null
  lengthInMeters: number | null
  durationInMinutes: number | null
}

export type ConvoySegmentSumAggregateOutputType = {
  order: number | null
  lengthInMeters: number | null
  durationInMinutes: number | null
}

export type ConvoySegmentMinAggregateOutputType = {
  id: string | null
  convoyId: string | null
  name: string | null
  order: number | null
  lengthInMeters: number | null
  durationInMinutes: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ConvoySegmentMaxAggregateOutputType = {
  id: string | null
  convoyId: string | null
  name: string | null
  order: number | null
  lengthInMeters: number | null
  durationInMinutes: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ConvoySegmentCountAggregateOutputType = {
  id: number
  convoyId: number
  name: number
  order: number
  geometry: number
  lengthInMeters: number
  durationInMinutes: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type ConvoySegmentAvgAggregateInputType = {
  order?: true
  lengthInMeters?: true
  durationInMinutes?: true
}

export type ConvoySegmentSumAggregateInputType = {
  order?: true
  lengthInMeters?: true
  durationInMinutes?: true
}

export type ConvoySegmentMinAggregateInputType = {
  id?: true
  convoyId?: true
  name?: true
  order?: true
  lengthInMeters?: true
  durationInMinutes?: true
  createdAt?: true
  updatedAt?: true
}

export type ConvoySegmentMaxAggregateInputType = {
  id?: true
  convoyId?: true
  name?: true
  order?: true
  lengthInMeters?: true
  durationInMinutes?: true
  createdAt?: true
  updatedAt?: true
}

export type ConvoySegmentCountAggregateInputType = {
  id?: true
  convoyId?: true
  name?: true
  order?: true
  geometry?: true
  lengthInMeters?: true
  durationInMinutes?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type ConvoySegmentAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ConvoySegment to aggregate.
   */
  where?: Prisma.ConvoySegmentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ConvoySegments to fetch.
   */
  orderBy?: Prisma.ConvoySegmentOrderByWithRelationInput | Prisma.ConvoySegmentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ConvoySegmentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ConvoySegments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ConvoySegments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ConvoySegments
  **/
  _count?: true | ConvoySegmentCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ConvoySegmentAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ConvoySegmentSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ConvoySegmentMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ConvoySegmentMaxAggregateInputType
}

export type GetConvoySegmentAggregateType<T extends ConvoySegmentAggregateArgs> = {
      [P in keyof T & keyof AggregateConvoySegment]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateConvoySegment[P]>
    : Prisma.GetScalarType<T[P], AggregateConvoySegment[P]>
}




export type ConvoySegmentGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ConvoySegmentWhereInput
  orderBy?: Prisma.ConvoySegmentOrderByWithAggregationInput | Prisma.ConvoySegmentOrderByWithAggregationInput[]
  by: Prisma.ConvoySegmentScalarFieldEnum[] | Prisma.ConvoySegmentScalarFieldEnum
  having?: Prisma.ConvoySegmentScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ConvoySegmentCountAggregateInputType | true
  _avg?: ConvoySegmentAvgAggregateInputType
  _sum?: ConvoySegmentSumAggregateInputType
  _min?: ConvoySegmentMinAggregateInputType
  _max?: ConvoySegmentMaxAggregateInputType
}

export type ConvoySegmentGroupByOutputType = {
  id: string
  convoyId: string
  name: string
  order: number
  geometry: runtime.JsonValue
  lengthInMeters: number
  durationInMinutes: number
  createdAt: Date
  updatedAt: Date
  _count: ConvoySegmentCountAggregateOutputType | null
  _avg: ConvoySegmentAvgAggregateOutputType | null
  _sum: ConvoySegmentSumAggregateOutputType | null
  _min: ConvoySegmentMinAggregateOutputType | null
  _max: ConvoySegmentMaxAggregateOutputType | null
}

export type GetConvoySegmentGroupByPayload<T extends ConvoySegmentGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ConvoySegmentGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ConvoySegmentGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ConvoySegmentGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ConvoySegmentGroupByOutputType[P]>
      }
    >
  >



export type ConvoySegmentWhereInput = {
  AND?: Prisma.ConvoySegmentWhereInput | Prisma.ConvoySegmentWhereInput[]
  OR?: Prisma.ConvoySegmentWhereInput[]
  NOT?: Prisma.ConvoySegmentWhereInput | Prisma.ConvoySegmentWhereInput[]
  id?: Prisma.StringFilter<"ConvoySegment"> | string
  convoyId?: Prisma.StringFilter<"ConvoySegment"> | string
  name?: Prisma.StringFilter<"ConvoySegment"> | string
  order?: Prisma.IntFilter<"ConvoySegment"> | number
  geometry?: Prisma.JsonFilter<"ConvoySegment">
  lengthInMeters?: Prisma.FloatFilter<"ConvoySegment"> | number
  durationInMinutes?: Prisma.FloatFilter<"ConvoySegment"> | number
  createdAt?: Prisma.DateTimeFilter<"ConvoySegment"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ConvoySegment"> | Date | string
  convoy?: Prisma.XOR<Prisma.ConvoyScalarRelationFilter, Prisma.ConvoyWhereInput>
  poi?: Prisma.XOR<Prisma.ConvoyPOINullableScalarRelationFilter, Prisma.ConvoyPOIWhereInput> | null
}

export type ConvoySegmentOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  convoyId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  order?: Prisma.SortOrder
  geometry?: Prisma.SortOrder
  lengthInMeters?: Prisma.SortOrder
  durationInMinutes?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  convoy?: Prisma.ConvoyOrderByWithRelationInput
  poi?: Prisma.ConvoyPOIOrderByWithRelationInput
}

export type ConvoySegmentWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.ConvoySegmentWhereInput | Prisma.ConvoySegmentWhereInput[]
  OR?: Prisma.ConvoySegmentWhereInput[]
  NOT?: Prisma.ConvoySegmentWhereInput | Prisma.ConvoySegmentWhereInput[]
  convoyId?: Prisma.StringFilter<"ConvoySegment"> | string
  name?: Prisma.StringFilter<"ConvoySegment"> | string
  order?: Prisma.IntFilter<"ConvoySegment"> | number
  geometry?: Prisma.JsonFilter<"ConvoySegment">
  lengthInMeters?: Prisma.FloatFilter<"ConvoySegment"> | number
  durationInMinutes?: Prisma.FloatFilter<"ConvoySegment"> | number
  createdAt?: Prisma.DateTimeFilter<"ConvoySegment"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ConvoySegment"> | Date | string
  convoy?: Prisma.XOR<Prisma.ConvoyScalarRelationFilter, Prisma.ConvoyWhereInput>
  poi?: Prisma.XOR<Prisma.ConvoyPOINullableScalarRelationFilter, Prisma.ConvoyPOIWhereInput> | null
}, "id">

export type ConvoySegmentOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  convoyId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  order?: Prisma.SortOrder
  geometry?: Prisma.SortOrder
  lengthInMeters?: Prisma.SortOrder
  durationInMinutes?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.ConvoySegmentCountOrderByAggregateInput
  _avg?: Prisma.ConvoySegmentAvgOrderByAggregateInput
  _max?: Prisma.ConvoySegmentMaxOrderByAggregateInput
  _min?: Prisma.ConvoySegmentMinOrderByAggregateInput
  _sum?: Prisma.ConvoySegmentSumOrderByAggregateInput
}

export type ConvoySegmentScalarWhereWithAggregatesInput = {
  AND?: Prisma.ConvoySegmentScalarWhereWithAggregatesInput | Prisma.ConvoySegmentScalarWhereWithAggregatesInput[]
  OR?: Prisma.ConvoySegmentScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ConvoySegmentScalarWhereWithAggregatesInput | Prisma.ConvoySegmentScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ConvoySegment"> | string
  convoyId?: Prisma.StringWithAggregatesFilter<"ConvoySegment"> | string
  name?: Prisma.StringWithAggregatesFilter<"ConvoySegment"> | string
  order?: Prisma.IntWithAggregatesFilter<"ConvoySegment"> | number
  geometry?: Prisma.JsonWithAggregatesFilter<"ConvoySegment">
  lengthInMeters?: Prisma.FloatWithAggregatesFilter<"ConvoySegment"> | number
  durationInMinutes?: Prisma.FloatWithAggregatesFilter<"ConvoySegment"> | number
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"ConvoySegment"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"ConvoySegment"> | Date | string
}

export type ConvoySegmentCreateInput = {
  id?: string
  name?: string
  order: number
  geometry: Prisma.JsonNullValueInput | runtime.InputJsonValue
  lengthInMeters: number
  durationInMinutes: number
  createdAt?: Date | string
  updatedAt?: Date | string
  convoy: Prisma.ConvoyCreateNestedOneWithoutSegmentsInput
  poi?: Prisma.ConvoyPOICreateNestedOneWithoutSegmentInput
}

export type ConvoySegmentUncheckedCreateInput = {
  id?: string
  convoyId: string
  name?: string
  order: number
  geometry: Prisma.JsonNullValueInput | runtime.InputJsonValue
  lengthInMeters: number
  durationInMinutes: number
  createdAt?: Date | string
  updatedAt?: Date | string
  poi?: Prisma.ConvoyPOIUncheckedCreateNestedOneWithoutSegmentInput
}

export type ConvoySegmentUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  geometry?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  lengthInMeters?: Prisma.FloatFieldUpdateOperationsInput | number
  durationInMinutes?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  convoy?: Prisma.ConvoyUpdateOneRequiredWithoutSegmentsNestedInput
  poi?: Prisma.ConvoyPOIUpdateOneWithoutSegmentNestedInput
}

export type ConvoySegmentUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  convoyId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  geometry?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  lengthInMeters?: Prisma.FloatFieldUpdateOperationsInput | number
  durationInMinutes?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  poi?: Prisma.ConvoyPOIUncheckedUpdateOneWithoutSegmentNestedInput
}

export type ConvoySegmentCreateManyInput = {
  id?: string
  convoyId: string
  name?: string
  order: number
  geometry: Prisma.JsonNullValueInput | runtime.InputJsonValue
  lengthInMeters: number
  durationInMinutes: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ConvoySegmentUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  geometry?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  lengthInMeters?: Prisma.FloatFieldUpdateOperationsInput | number
  durationInMinutes?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ConvoySegmentUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  convoyId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  geometry?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  lengthInMeters?: Prisma.FloatFieldUpdateOperationsInput | number
  durationInMinutes?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ConvoySegmentListRelationFilter = {
  every?: Prisma.ConvoySegmentWhereInput
  some?: Prisma.ConvoySegmentWhereInput
  none?: Prisma.ConvoySegmentWhereInput
}

export type ConvoySegmentOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ConvoySegmentCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  convoyId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  order?: Prisma.SortOrder
  geometry?: Prisma.SortOrder
  lengthInMeters?: Prisma.SortOrder
  durationInMinutes?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ConvoySegmentAvgOrderByAggregateInput = {
  order?: Prisma.SortOrder
  lengthInMeters?: Prisma.SortOrder
  durationInMinutes?: Prisma.SortOrder
}

export type ConvoySegmentMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  convoyId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  order?: Prisma.SortOrder
  lengthInMeters?: Prisma.SortOrder
  durationInMinutes?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ConvoySegmentMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  convoyId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  order?: Prisma.SortOrder
  lengthInMeters?: Prisma.SortOrder
  durationInMinutes?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ConvoySegmentSumOrderByAggregateInput = {
  order?: Prisma.SortOrder
  lengthInMeters?: Prisma.SortOrder
  durationInMinutes?: Prisma.SortOrder
}

export type ConvoySegmentScalarRelationFilter = {
  is?: Prisma.ConvoySegmentWhereInput
  isNot?: Prisma.ConvoySegmentWhereInput
}

export type ConvoySegmentCreateNestedManyWithoutConvoyInput = {
  create?: Prisma.XOR<Prisma.ConvoySegmentCreateWithoutConvoyInput, Prisma.ConvoySegmentUncheckedCreateWithoutConvoyInput> | Prisma.ConvoySegmentCreateWithoutConvoyInput[] | Prisma.ConvoySegmentUncheckedCreateWithoutConvoyInput[]
  connectOrCreate?: Prisma.ConvoySegmentCreateOrConnectWithoutConvoyInput | Prisma.ConvoySegmentCreateOrConnectWithoutConvoyInput[]
  createMany?: Prisma.ConvoySegmentCreateManyConvoyInputEnvelope
  connect?: Prisma.ConvoySegmentWhereUniqueInput | Prisma.ConvoySegmentWhereUniqueInput[]
}

export type ConvoySegmentUncheckedCreateNestedManyWithoutConvoyInput = {
  create?: Prisma.XOR<Prisma.ConvoySegmentCreateWithoutConvoyInput, Prisma.ConvoySegmentUncheckedCreateWithoutConvoyInput> | Prisma.ConvoySegmentCreateWithoutConvoyInput[] | Prisma.ConvoySegmentUncheckedCreateWithoutConvoyInput[]
  connectOrCreate?: Prisma.ConvoySegmentCreateOrConnectWithoutConvoyInput | Prisma.ConvoySegmentCreateOrConnectWithoutConvoyInput[]
  createMany?: Prisma.ConvoySegmentCreateManyConvoyInputEnvelope
  connect?: Prisma.ConvoySegmentWhereUniqueInput | Prisma.ConvoySegmentWhereUniqueInput[]
}

export type ConvoySegmentUpdateManyWithoutConvoyNestedInput = {
  create?: Prisma.XOR<Prisma.ConvoySegmentCreateWithoutConvoyInput, Prisma.ConvoySegmentUncheckedCreateWithoutConvoyInput> | Prisma.ConvoySegmentCreateWithoutConvoyInput[] | Prisma.ConvoySegmentUncheckedCreateWithoutConvoyInput[]
  connectOrCreate?: Prisma.ConvoySegmentCreateOrConnectWithoutConvoyInput | Prisma.ConvoySegmentCreateOrConnectWithoutConvoyInput[]
  upsert?: Prisma.ConvoySegmentUpsertWithWhereUniqueWithoutConvoyInput | Prisma.ConvoySegmentUpsertWithWhereUniqueWithoutConvoyInput[]
  createMany?: Prisma.ConvoySegmentCreateManyConvoyInputEnvelope
  set?: Prisma.ConvoySegmentWhereUniqueInput | Prisma.ConvoySegmentWhereUniqueInput[]
  disconnect?: Prisma.ConvoySegmentWhereUniqueInput | Prisma.ConvoySegmentWhereUniqueInput[]
  delete?: Prisma.ConvoySegmentWhereUniqueInput | Prisma.ConvoySegmentWhereUniqueInput[]
  connect?: Prisma.ConvoySegmentWhereUniqueInput | Prisma.ConvoySegmentWhereUniqueInput[]
  update?: Prisma.ConvoySegmentUpdateWithWhereUniqueWithoutConvoyInput | Prisma.ConvoySegmentUpdateWithWhereUniqueWithoutConvoyInput[]
  updateMany?: Prisma.ConvoySegmentUpdateManyWithWhereWithoutConvoyInput | Prisma.ConvoySegmentUpdateManyWithWhereWithoutConvoyInput[]
  deleteMany?: Prisma.ConvoySegmentScalarWhereInput | Prisma.ConvoySegmentScalarWhereInput[]
}

export type ConvoySegmentUncheckedUpdateManyWithoutConvoyNestedInput = {
  create?: Prisma.XOR<Prisma.ConvoySegmentCreateWithoutConvoyInput, Prisma.ConvoySegmentUncheckedCreateWithoutConvoyInput> | Prisma.ConvoySegmentCreateWithoutConvoyInput[] | Prisma.ConvoySegmentUncheckedCreateWithoutConvoyInput[]
  connectOrCreate?: Prisma.ConvoySegmentCreateOrConnectWithoutConvoyInput | Prisma.ConvoySegmentCreateOrConnectWithoutConvoyInput[]
  upsert?: Prisma.ConvoySegmentUpsertWithWhereUniqueWithoutConvoyInput | Prisma.ConvoySegmentUpsertWithWhereUniqueWithoutConvoyInput[]
  createMany?: Prisma.ConvoySegmentCreateManyConvoyInputEnvelope
  set?: Prisma.ConvoySegmentWhereUniqueInput | Prisma.ConvoySegmentWhereUniqueInput[]
  disconnect?: Prisma.ConvoySegmentWhereUniqueInput | Prisma.ConvoySegmentWhereUniqueInput[]
  delete?: Prisma.ConvoySegmentWhereUniqueInput | Prisma.ConvoySegmentWhereUniqueInput[]
  connect?: Prisma.ConvoySegmentWhereUniqueInput | Prisma.ConvoySegmentWhereUniqueInput[]
  update?: Prisma.ConvoySegmentUpdateWithWhereUniqueWithoutConvoyInput | Prisma.ConvoySegmentUpdateWithWhereUniqueWithoutConvoyInput[]
  updateMany?: Prisma.ConvoySegmentUpdateManyWithWhereWithoutConvoyInput | Prisma.ConvoySegmentUpdateManyWithWhereWithoutConvoyInput[]
  deleteMany?: Prisma.ConvoySegmentScalarWhereInput | Prisma.ConvoySegmentScalarWhereInput[]
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type FloatFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type ConvoySegmentCreateNestedOneWithoutPoiInput = {
  create?: Prisma.XOR<Prisma.ConvoySegmentCreateWithoutPoiInput, Prisma.ConvoySegmentUncheckedCreateWithoutPoiInput>
  connectOrCreate?: Prisma.ConvoySegmentCreateOrConnectWithoutPoiInput
  connect?: Prisma.ConvoySegmentWhereUniqueInput
}

export type ConvoySegmentUpdateOneRequiredWithoutPoiNestedInput = {
  create?: Prisma.XOR<Prisma.ConvoySegmentCreateWithoutPoiInput, Prisma.ConvoySegmentUncheckedCreateWithoutPoiInput>
  connectOrCreate?: Prisma.ConvoySegmentCreateOrConnectWithoutPoiInput
  upsert?: Prisma.ConvoySegmentUpsertWithoutPoiInput
  connect?: Prisma.ConvoySegmentWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ConvoySegmentUpdateToOneWithWhereWithoutPoiInput, Prisma.ConvoySegmentUpdateWithoutPoiInput>, Prisma.ConvoySegmentUncheckedUpdateWithoutPoiInput>
}

export type ConvoySegmentCreateWithoutConvoyInput = {
  id?: string
  name?: string
  order: number
  geometry: Prisma.JsonNullValueInput | runtime.InputJsonValue
  lengthInMeters: number
  durationInMinutes: number
  createdAt?: Date | string
  updatedAt?: Date | string
  poi?: Prisma.ConvoyPOICreateNestedOneWithoutSegmentInput
}

export type ConvoySegmentUncheckedCreateWithoutConvoyInput = {
  id?: string
  name?: string
  order: number
  geometry: Prisma.JsonNullValueInput | runtime.InputJsonValue
  lengthInMeters: number
  durationInMinutes: number
  createdAt?: Date | string
  updatedAt?: Date | string
  poi?: Prisma.ConvoyPOIUncheckedCreateNestedOneWithoutSegmentInput
}

export type ConvoySegmentCreateOrConnectWithoutConvoyInput = {
  where: Prisma.ConvoySegmentWhereUniqueInput
  create: Prisma.XOR<Prisma.ConvoySegmentCreateWithoutConvoyInput, Prisma.ConvoySegmentUncheckedCreateWithoutConvoyInput>
}

export type ConvoySegmentCreateManyConvoyInputEnvelope = {
  data: Prisma.ConvoySegmentCreateManyConvoyInput | Prisma.ConvoySegmentCreateManyConvoyInput[]
  skipDuplicates?: boolean
}

export type ConvoySegmentUpsertWithWhereUniqueWithoutConvoyInput = {
  where: Prisma.ConvoySegmentWhereUniqueInput
  update: Prisma.XOR<Prisma.ConvoySegmentUpdateWithoutConvoyInput, Prisma.ConvoySegmentUncheckedUpdateWithoutConvoyInput>
  create: Prisma.XOR<Prisma.ConvoySegmentCreateWithoutConvoyInput, Prisma.ConvoySegmentUncheckedCreateWithoutConvoyInput>
}

export type ConvoySegmentUpdateWithWhereUniqueWithoutConvoyInput = {
  where: Prisma.ConvoySegmentWhereUniqueInput
  data: Prisma.XOR<Prisma.ConvoySegmentUpdateWithoutConvoyInput, Prisma.ConvoySegmentUncheckedUpdateWithoutConvoyInput>
}

export type ConvoySegmentUpdateManyWithWhereWithoutConvoyInput = {
  where: Prisma.ConvoySegmentScalarWhereInput
  data: Prisma.XOR<Prisma.ConvoySegmentUpdateManyMutationInput, Prisma.ConvoySegmentUncheckedUpdateManyWithoutConvoyInput>
}

export type ConvoySegmentScalarWhereInput = {
  AND?: Prisma.ConvoySegmentScalarWhereInput | Prisma.ConvoySegmentScalarWhereInput[]
  OR?: Prisma.ConvoySegmentScalarWhereInput[]
  NOT?: Prisma.ConvoySegmentScalarWhereInput | Prisma.ConvoySegmentScalarWhereInput[]
  id?: Prisma.StringFilter<"ConvoySegment"> | string
  convoyId?: Prisma.StringFilter<"ConvoySegment"> | string
  name?: Prisma.StringFilter<"ConvoySegment"> | string
  order?: Prisma.IntFilter<"ConvoySegment"> | number
  geometry?: Prisma.JsonFilter<"ConvoySegment">
  lengthInMeters?: Prisma.FloatFilter<"ConvoySegment"> | number
  durationInMinutes?: Prisma.FloatFilter<"ConvoySegment"> | number
  createdAt?: Prisma.DateTimeFilter<"ConvoySegment"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ConvoySegment"> | Date | string
}

export type ConvoySegmentCreateWithoutPoiInput = {
  id?: string
  name?: string
  order: number
  geometry: Prisma.JsonNullValueInput | runtime.InputJsonValue
  lengthInMeters: number
  durationInMinutes: number
  createdAt?: Date | string
  updatedAt?: Date | string
  convoy: Prisma.ConvoyCreateNestedOneWithoutSegmentsInput
}

export type ConvoySegmentUncheckedCreateWithoutPoiInput = {
  id?: string
  convoyId: string
  name?: string
  order: number
  geometry: Prisma.JsonNullValueInput | runtime.InputJsonValue
  lengthInMeters: number
  durationInMinutes: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ConvoySegmentCreateOrConnectWithoutPoiInput = {
  where: Prisma.ConvoySegmentWhereUniqueInput
  create: Prisma.XOR<Prisma.ConvoySegmentCreateWithoutPoiInput, Prisma.ConvoySegmentUncheckedCreateWithoutPoiInput>
}

export type ConvoySegmentUpsertWithoutPoiInput = {
  update: Prisma.XOR<Prisma.ConvoySegmentUpdateWithoutPoiInput, Prisma.ConvoySegmentUncheckedUpdateWithoutPoiInput>
  create: Prisma.XOR<Prisma.ConvoySegmentCreateWithoutPoiInput, Prisma.ConvoySegmentUncheckedCreateWithoutPoiInput>
  where?: Prisma.ConvoySegmentWhereInput
}

export type ConvoySegmentUpdateToOneWithWhereWithoutPoiInput = {
  where?: Prisma.ConvoySegmentWhereInput
  data: Prisma.XOR<Prisma.ConvoySegmentUpdateWithoutPoiInput, Prisma.ConvoySegmentUncheckedUpdateWithoutPoiInput>
}

export type ConvoySegmentUpdateWithoutPoiInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  geometry?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  lengthInMeters?: Prisma.FloatFieldUpdateOperationsInput | number
  durationInMinutes?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  convoy?: Prisma.ConvoyUpdateOneRequiredWithoutSegmentsNestedInput
}

export type ConvoySegmentUncheckedUpdateWithoutPoiInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  convoyId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  geometry?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  lengthInMeters?: Prisma.FloatFieldUpdateOperationsInput | number
  durationInMinutes?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ConvoySegmentCreateManyConvoyInput = {
  id?: string
  name?: string
  order: number
  geometry: Prisma.JsonNullValueInput | runtime.InputJsonValue
  lengthInMeters: number
  durationInMinutes: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ConvoySegmentUpdateWithoutConvoyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  geometry?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  lengthInMeters?: Prisma.FloatFieldUpdateOperationsInput | number
  durationInMinutes?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  poi?: Prisma.ConvoyPOIUpdateOneWithoutSegmentNestedInput
}

export type ConvoySegmentUncheckedUpdateWithoutConvoyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  geometry?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  lengthInMeters?: Prisma.FloatFieldUpdateOperationsInput | number
  durationInMinutes?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  poi?: Prisma.ConvoyPOIUncheckedUpdateOneWithoutSegmentNestedInput
}

export type ConvoySegmentUncheckedUpdateManyWithoutConvoyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  geometry?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  lengthInMeters?: Prisma.FloatFieldUpdateOperationsInput | number
  durationInMinutes?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type ConvoySegmentSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  convoyId?: boolean
  name?: boolean
  order?: boolean
  geometry?: boolean
  lengthInMeters?: boolean
  durationInMinutes?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  convoy?: boolean | Prisma.ConvoyDefaultArgs<ExtArgs>
  poi?: boolean | Prisma.ConvoySegment$poiArgs<ExtArgs>
}, ExtArgs["result"]["convoySegment"]>

export type ConvoySegmentSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  convoyId?: boolean
  name?: boolean
  order?: boolean
  geometry?: boolean
  lengthInMeters?: boolean
  durationInMinutes?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  convoy?: boolean | Prisma.ConvoyDefaultArgs<ExtArgs>
}, ExtArgs["result"]["convoySegment"]>

export type ConvoySegmentSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  convoyId?: boolean
  name?: boolean
  order?: boolean
  geometry?: boolean
  lengthInMeters?: boolean
  durationInMinutes?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  convoy?: boolean | Prisma.ConvoyDefaultArgs<ExtArgs>
}, ExtArgs["result"]["convoySegment"]>

export type ConvoySegmentSelectScalar = {
  id?: boolean
  convoyId?: boolean
  name?: boolean
  order?: boolean
  geometry?: boolean
  lengthInMeters?: boolean
  durationInMinutes?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type ConvoySegmentOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "convoyId" | "name" | "order" | "geometry" | "lengthInMeters" | "durationInMinutes" | "createdAt" | "updatedAt", ExtArgs["result"]["convoySegment"]>
export type ConvoySegmentInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  convoy?: boolean | Prisma.ConvoyDefaultArgs<ExtArgs>
  poi?: boolean | Prisma.ConvoySegment$poiArgs<ExtArgs>
}
export type ConvoySegmentIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  convoy?: boolean | Prisma.ConvoyDefaultArgs<ExtArgs>
}
export type ConvoySegmentIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  convoy?: boolean | Prisma.ConvoyDefaultArgs<ExtArgs>
}

export type $ConvoySegmentPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ConvoySegment"
  objects: {
    convoy: Prisma.$ConvoyPayload<ExtArgs>
    poi: Prisma.$ConvoyPOIPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    convoyId: string
    name: string
    order: number
    geometry: runtime.JsonValue
    lengthInMeters: number
    durationInMinutes: number
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["convoySegment"]>
  composites: {}
}

export type ConvoySegmentGetPayload<S extends boolean | null | undefined | ConvoySegmentDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ConvoySegmentPayload, S>

export type ConvoySegmentCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ConvoySegmentFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ConvoySegmentCountAggregateInputType | true
  }

export interface ConvoySegmentDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ConvoySegment'], meta: { name: 'ConvoySegment' } }
  /**
   * Find zero or one ConvoySegment that matches the filter.
   * @param {ConvoySegmentFindUniqueArgs} args - Arguments to find a ConvoySegment
   * @example
   * // Get one ConvoySegment
   * const convoySegment = await prisma.convoySegment.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ConvoySegmentFindUniqueArgs>(args: Prisma.SelectSubset<T, ConvoySegmentFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ConvoySegmentClient<runtime.Types.Result.GetResult<Prisma.$ConvoySegmentPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ConvoySegment that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ConvoySegmentFindUniqueOrThrowArgs} args - Arguments to find a ConvoySegment
   * @example
   * // Get one ConvoySegment
   * const convoySegment = await prisma.convoySegment.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ConvoySegmentFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ConvoySegmentFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ConvoySegmentClient<runtime.Types.Result.GetResult<Prisma.$ConvoySegmentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ConvoySegment that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ConvoySegmentFindFirstArgs} args - Arguments to find a ConvoySegment
   * @example
   * // Get one ConvoySegment
   * const convoySegment = await prisma.convoySegment.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ConvoySegmentFindFirstArgs>(args?: Prisma.SelectSubset<T, ConvoySegmentFindFirstArgs<ExtArgs>>): Prisma.Prisma__ConvoySegmentClient<runtime.Types.Result.GetResult<Prisma.$ConvoySegmentPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ConvoySegment that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ConvoySegmentFindFirstOrThrowArgs} args - Arguments to find a ConvoySegment
   * @example
   * // Get one ConvoySegment
   * const convoySegment = await prisma.convoySegment.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ConvoySegmentFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ConvoySegmentFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ConvoySegmentClient<runtime.Types.Result.GetResult<Prisma.$ConvoySegmentPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ConvoySegments that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ConvoySegmentFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ConvoySegments
   * const convoySegments = await prisma.convoySegment.findMany()
   * 
   * // Get first 10 ConvoySegments
   * const convoySegments = await prisma.convoySegment.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const convoySegmentWithIdOnly = await prisma.convoySegment.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ConvoySegmentFindManyArgs>(args?: Prisma.SelectSubset<T, ConvoySegmentFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ConvoySegmentPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ConvoySegment.
   * @param {ConvoySegmentCreateArgs} args - Arguments to create a ConvoySegment.
   * @example
   * // Create one ConvoySegment
   * const ConvoySegment = await prisma.convoySegment.create({
   *   data: {
   *     // ... data to create a ConvoySegment
   *   }
   * })
   * 
   */
  create<T extends ConvoySegmentCreateArgs>(args: Prisma.SelectSubset<T, ConvoySegmentCreateArgs<ExtArgs>>): Prisma.Prisma__ConvoySegmentClient<runtime.Types.Result.GetResult<Prisma.$ConvoySegmentPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ConvoySegments.
   * @param {ConvoySegmentCreateManyArgs} args - Arguments to create many ConvoySegments.
   * @example
   * // Create many ConvoySegments
   * const convoySegment = await prisma.convoySegment.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ConvoySegmentCreateManyArgs>(args?: Prisma.SelectSubset<T, ConvoySegmentCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ConvoySegments and returns the data saved in the database.
   * @param {ConvoySegmentCreateManyAndReturnArgs} args - Arguments to create many ConvoySegments.
   * @example
   * // Create many ConvoySegments
   * const convoySegment = await prisma.convoySegment.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ConvoySegments and only return the `id`
   * const convoySegmentWithIdOnly = await prisma.convoySegment.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ConvoySegmentCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ConvoySegmentCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ConvoySegmentPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ConvoySegment.
   * @param {ConvoySegmentDeleteArgs} args - Arguments to delete one ConvoySegment.
   * @example
   * // Delete one ConvoySegment
   * const ConvoySegment = await prisma.convoySegment.delete({
   *   where: {
   *     // ... filter to delete one ConvoySegment
   *   }
   * })
   * 
   */
  delete<T extends ConvoySegmentDeleteArgs>(args: Prisma.SelectSubset<T, ConvoySegmentDeleteArgs<ExtArgs>>): Prisma.Prisma__ConvoySegmentClient<runtime.Types.Result.GetResult<Prisma.$ConvoySegmentPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ConvoySegment.
   * @param {ConvoySegmentUpdateArgs} args - Arguments to update one ConvoySegment.
   * @example
   * // Update one ConvoySegment
   * const convoySegment = await prisma.convoySegment.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ConvoySegmentUpdateArgs>(args: Prisma.SelectSubset<T, ConvoySegmentUpdateArgs<ExtArgs>>): Prisma.Prisma__ConvoySegmentClient<runtime.Types.Result.GetResult<Prisma.$ConvoySegmentPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ConvoySegments.
   * @param {ConvoySegmentDeleteManyArgs} args - Arguments to filter ConvoySegments to delete.
   * @example
   * // Delete a few ConvoySegments
   * const { count } = await prisma.convoySegment.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ConvoySegmentDeleteManyArgs>(args?: Prisma.SelectSubset<T, ConvoySegmentDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ConvoySegments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ConvoySegmentUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ConvoySegments
   * const convoySegment = await prisma.convoySegment.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ConvoySegmentUpdateManyArgs>(args: Prisma.SelectSubset<T, ConvoySegmentUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ConvoySegments and returns the data updated in the database.
   * @param {ConvoySegmentUpdateManyAndReturnArgs} args - Arguments to update many ConvoySegments.
   * @example
   * // Update many ConvoySegments
   * const convoySegment = await prisma.convoySegment.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ConvoySegments and only return the `id`
   * const convoySegmentWithIdOnly = await prisma.convoySegment.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ConvoySegmentUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ConvoySegmentUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ConvoySegmentPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ConvoySegment.
   * @param {ConvoySegmentUpsertArgs} args - Arguments to update or create a ConvoySegment.
   * @example
   * // Update or create a ConvoySegment
   * const convoySegment = await prisma.convoySegment.upsert({
   *   create: {
   *     // ... data to create a ConvoySegment
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ConvoySegment we want to update
   *   }
   * })
   */
  upsert<T extends ConvoySegmentUpsertArgs>(args: Prisma.SelectSubset<T, ConvoySegmentUpsertArgs<ExtArgs>>): Prisma.Prisma__ConvoySegmentClient<runtime.Types.Result.GetResult<Prisma.$ConvoySegmentPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ConvoySegments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ConvoySegmentCountArgs} args - Arguments to filter ConvoySegments to count.
   * @example
   * // Count the number of ConvoySegments
   * const count = await prisma.convoySegment.count({
   *   where: {
   *     // ... the filter for the ConvoySegments we want to count
   *   }
   * })
  **/
  count<T extends ConvoySegmentCountArgs>(
    args?: Prisma.Subset<T, ConvoySegmentCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ConvoySegmentCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ConvoySegment.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ConvoySegmentAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ConvoySegmentAggregateArgs>(args: Prisma.Subset<T, ConvoySegmentAggregateArgs>): Prisma.PrismaPromise<GetConvoySegmentAggregateType<T>>

  /**
   * Group by ConvoySegment.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ConvoySegmentGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ConvoySegmentGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ConvoySegmentGroupByArgs['orderBy'] }
      : { orderBy?: ConvoySegmentGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ConvoySegmentGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetConvoySegmentGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ConvoySegment model
 */
readonly fields: ConvoySegmentFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ConvoySegment.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ConvoySegmentClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  convoy<T extends Prisma.ConvoyDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ConvoyDefaultArgs<ExtArgs>>): Prisma.Prisma__ConvoyClient<runtime.Types.Result.GetResult<Prisma.$ConvoyPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  poi<T extends Prisma.ConvoySegment$poiArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ConvoySegment$poiArgs<ExtArgs>>): Prisma.Prisma__ConvoyPOIClient<runtime.Types.Result.GetResult<Prisma.$ConvoyPOIPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ConvoySegment model
 */
export interface ConvoySegmentFieldRefs {
  readonly id: Prisma.FieldRef<"ConvoySegment", 'String'>
  readonly convoyId: Prisma.FieldRef<"ConvoySegment", 'String'>
  readonly name: Prisma.FieldRef<"ConvoySegment", 'String'>
  readonly order: Prisma.FieldRef<"ConvoySegment", 'Int'>
  readonly geometry: Prisma.FieldRef<"ConvoySegment", 'Json'>
  readonly lengthInMeters: Prisma.FieldRef<"ConvoySegment", 'Float'>
  readonly durationInMinutes: Prisma.FieldRef<"ConvoySegment", 'Float'>
  readonly createdAt: Prisma.FieldRef<"ConvoySegment", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"ConvoySegment", 'DateTime'>
}
    

// Custom InputTypes
/**
 * ConvoySegment findUnique
 */
export type ConvoySegmentFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ConvoySegment
   */
  select?: Prisma.ConvoySegmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ConvoySegment
   */
  omit?: Prisma.ConvoySegmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ConvoySegmentInclude<ExtArgs> | null
  /**
   * Filter, which ConvoySegment to fetch.
   */
  where: Prisma.ConvoySegmentWhereUniqueInput
}

/**
 * ConvoySegment findUniqueOrThrow
 */
export type ConvoySegmentFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ConvoySegment
   */
  select?: Prisma.ConvoySegmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ConvoySegment
   */
  omit?: Prisma.ConvoySegmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ConvoySegmentInclude<ExtArgs> | null
  /**
   * Filter, which ConvoySegment to fetch.
   */
  where: Prisma.ConvoySegmentWhereUniqueInput
}

/**
 * ConvoySegment findFirst
 */
export type ConvoySegmentFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ConvoySegment
   */
  select?: Prisma.ConvoySegmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ConvoySegment
   */
  omit?: Prisma.ConvoySegmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ConvoySegmentInclude<ExtArgs> | null
  /**
   * Filter, which ConvoySegment to fetch.
   */
  where?: Prisma.ConvoySegmentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ConvoySegments to fetch.
   */
  orderBy?: Prisma.ConvoySegmentOrderByWithRelationInput | Prisma.ConvoySegmentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ConvoySegments.
   */
  cursor?: Prisma.ConvoySegmentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ConvoySegments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ConvoySegments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ConvoySegments.
   */
  distinct?: Prisma.ConvoySegmentScalarFieldEnum | Prisma.ConvoySegmentScalarFieldEnum[]
}

/**
 * ConvoySegment findFirstOrThrow
 */
export type ConvoySegmentFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ConvoySegment
   */
  select?: Prisma.ConvoySegmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ConvoySegment
   */
  omit?: Prisma.ConvoySegmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ConvoySegmentInclude<ExtArgs> | null
  /**
   * Filter, which ConvoySegment to fetch.
   */
  where?: Prisma.ConvoySegmentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ConvoySegments to fetch.
   */
  orderBy?: Prisma.ConvoySegmentOrderByWithRelationInput | Prisma.ConvoySegmentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ConvoySegments.
   */
  cursor?: Prisma.ConvoySegmentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ConvoySegments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ConvoySegments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ConvoySegments.
   */
  distinct?: Prisma.ConvoySegmentScalarFieldEnum | Prisma.ConvoySegmentScalarFieldEnum[]
}

/**
 * ConvoySegment findMany
 */
export type ConvoySegmentFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ConvoySegment
   */
  select?: Prisma.ConvoySegmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ConvoySegment
   */
  omit?: Prisma.ConvoySegmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ConvoySegmentInclude<ExtArgs> | null
  /**
   * Filter, which ConvoySegments to fetch.
   */
  where?: Prisma.ConvoySegmentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ConvoySegments to fetch.
   */
  orderBy?: Prisma.ConvoySegmentOrderByWithRelationInput | Prisma.ConvoySegmentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ConvoySegments.
   */
  cursor?: Prisma.ConvoySegmentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ConvoySegments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ConvoySegments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ConvoySegments.
   */
  distinct?: Prisma.ConvoySegmentScalarFieldEnum | Prisma.ConvoySegmentScalarFieldEnum[]
}

/**
 * ConvoySegment create
 */
export type ConvoySegmentCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ConvoySegment
   */
  select?: Prisma.ConvoySegmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ConvoySegment
   */
  omit?: Prisma.ConvoySegmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ConvoySegmentInclude<ExtArgs> | null
  /**
   * The data needed to create a ConvoySegment.
   */
  data: Prisma.XOR<Prisma.ConvoySegmentCreateInput, Prisma.ConvoySegmentUncheckedCreateInput>
}

/**
 * ConvoySegment createMany
 */
export type ConvoySegmentCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ConvoySegments.
   */
  data: Prisma.ConvoySegmentCreateManyInput | Prisma.ConvoySegmentCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ConvoySegment createManyAndReturn
 */
export type ConvoySegmentCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ConvoySegment
   */
  select?: Prisma.ConvoySegmentSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ConvoySegment
   */
  omit?: Prisma.ConvoySegmentOmit<ExtArgs> | null
  /**
   * The data used to create many ConvoySegments.
   */
  data: Prisma.ConvoySegmentCreateManyInput | Prisma.ConvoySegmentCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ConvoySegmentIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ConvoySegment update
 */
export type ConvoySegmentUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ConvoySegment
   */
  select?: Prisma.ConvoySegmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ConvoySegment
   */
  omit?: Prisma.ConvoySegmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ConvoySegmentInclude<ExtArgs> | null
  /**
   * The data needed to update a ConvoySegment.
   */
  data: Prisma.XOR<Prisma.ConvoySegmentUpdateInput, Prisma.ConvoySegmentUncheckedUpdateInput>
  /**
   * Choose, which ConvoySegment to update.
   */
  where: Prisma.ConvoySegmentWhereUniqueInput
}

/**
 * ConvoySegment updateMany
 */
export type ConvoySegmentUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ConvoySegments.
   */
  data: Prisma.XOR<Prisma.ConvoySegmentUpdateManyMutationInput, Prisma.ConvoySegmentUncheckedUpdateManyInput>
  /**
   * Filter which ConvoySegments to update
   */
  where?: Prisma.ConvoySegmentWhereInput
  /**
   * Limit how many ConvoySegments to update.
   */
  limit?: number
}

/**
 * ConvoySegment updateManyAndReturn
 */
export type ConvoySegmentUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ConvoySegment
   */
  select?: Prisma.ConvoySegmentSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ConvoySegment
   */
  omit?: Prisma.ConvoySegmentOmit<ExtArgs> | null
  /**
   * The data used to update ConvoySegments.
   */
  data: Prisma.XOR<Prisma.ConvoySegmentUpdateManyMutationInput, Prisma.ConvoySegmentUncheckedUpdateManyInput>
  /**
   * Filter which ConvoySegments to update
   */
  where?: Prisma.ConvoySegmentWhereInput
  /**
   * Limit how many ConvoySegments to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ConvoySegmentIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ConvoySegment upsert
 */
export type ConvoySegmentUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ConvoySegment
   */
  select?: Prisma.ConvoySegmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ConvoySegment
   */
  omit?: Prisma.ConvoySegmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ConvoySegmentInclude<ExtArgs> | null
  /**
   * The filter to search for the ConvoySegment to update in case it exists.
   */
  where: Prisma.ConvoySegmentWhereUniqueInput
  /**
   * In case the ConvoySegment found by the `where` argument doesn't exist, create a new ConvoySegment with this data.
   */
  create: Prisma.XOR<Prisma.ConvoySegmentCreateInput, Prisma.ConvoySegmentUncheckedCreateInput>
  /**
   * In case the ConvoySegment was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ConvoySegmentUpdateInput, Prisma.ConvoySegmentUncheckedUpdateInput>
}

/**
 * ConvoySegment delete
 */
export type ConvoySegmentDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ConvoySegment
   */
  select?: Prisma.ConvoySegmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ConvoySegment
   */
  omit?: Prisma.ConvoySegmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ConvoySegmentInclude<ExtArgs> | null
  /**
   * Filter which ConvoySegment to delete.
   */
  where: Prisma.ConvoySegmentWhereUniqueInput
}

/**
 * ConvoySegment deleteMany
 */
export type ConvoySegmentDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ConvoySegments to delete
   */
  where?: Prisma.ConvoySegmentWhereInput
  /**
   * Limit how many ConvoySegments to delete.
   */
  limit?: number
}

/**
 * ConvoySegment.poi
 */
export type ConvoySegment$poiArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ConvoyPOI
   */
  select?: Prisma.ConvoyPOISelect<ExtArgs> | null
  /**
   * Omit specific fields from the ConvoyPOI
   */
  omit?: Prisma.ConvoyPOIOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ConvoyPOIInclude<ExtArgs> | null
  where?: Prisma.ConvoyPOIWhereInput
}

/**
 * ConvoySegment without action
 */
export type ConvoySegmentDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ConvoySegment
   */
  select?: Prisma.ConvoySegmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ConvoySegment
   */
  omit?: Prisma.ConvoySegmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ConvoySegmentInclude<ExtArgs> | null
}
