
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Convoy` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model Convoy
 * 
 */
export type ConvoyModel = runtime.Types.Result.DefaultSelection<Prisma.$ConvoyPayload>

export type AggregateConvoy = {
  _count: ConvoyCountAggregateOutputType | null
  _min: ConvoyMinAggregateOutputType | null
  _max: ConvoyMaxAggregateOutputType | null
}

export type ConvoyMinAggregateOutputType = {
  id: string | null
  status: $Enums.ConvoyStatus | null
  name: string | null
  accessCode: string | null
  organizerPasswordHash: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ConvoyMaxAggregateOutputType = {
  id: string | null
  status: $Enums.ConvoyStatus | null
  name: string | null
  accessCode: string | null
  organizerPasswordHash: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ConvoyCountAggregateOutputType = {
  id: number
  status: number
  name: number
  accessCode: number
  organizerPasswordHash: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type ConvoyMinAggregateInputType = {
  id?: true
  status?: true
  name?: true
  accessCode?: true
  organizerPasswordHash?: true
  createdAt?: true
  updatedAt?: true
}

export type ConvoyMaxAggregateInputType = {
  id?: true
  status?: true
  name?: true
  accessCode?: true
  organizerPasswordHash?: true
  createdAt?: true
  updatedAt?: true
}

export type ConvoyCountAggregateInputType = {
  id?: true
  status?: true
  name?: true
  accessCode?: true
  organizerPasswordHash?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type ConvoyAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Convoy to aggregate.
   */
  where?: Prisma.ConvoyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Convoys to fetch.
   */
  orderBy?: Prisma.ConvoyOrderByWithRelationInput | Prisma.ConvoyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ConvoyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Convoys from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Convoys.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Convoys
  **/
  _count?: true | ConvoyCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ConvoyMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ConvoyMaxAggregateInputType
}

export type GetConvoyAggregateType<T extends ConvoyAggregateArgs> = {
      [P in keyof T & keyof AggregateConvoy]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateConvoy[P]>
    : Prisma.GetScalarType<T[P], AggregateConvoy[P]>
}




export type ConvoyGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ConvoyWhereInput
  orderBy?: Prisma.ConvoyOrderByWithAggregationInput | Prisma.ConvoyOrderByWithAggregationInput[]
  by: Prisma.ConvoyScalarFieldEnum[] | Prisma.ConvoyScalarFieldEnum
  having?: Prisma.ConvoyScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ConvoyCountAggregateInputType | true
  _min?: ConvoyMinAggregateInputType
  _max?: ConvoyMaxAggregateInputType
}

export type ConvoyGroupByOutputType = {
  id: string
  status: $Enums.ConvoyStatus
  name: string
  accessCode: string
  organizerPasswordHash: string
  createdAt: Date
  updatedAt: Date
  _count: ConvoyCountAggregateOutputType | null
  _min: ConvoyMinAggregateOutputType | null
  _max: ConvoyMaxAggregateOutputType | null
}

export type GetConvoyGroupByPayload<T extends ConvoyGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ConvoyGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ConvoyGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ConvoyGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ConvoyGroupByOutputType[P]>
      }
    >
  >



export type ConvoyWhereInput = {
  AND?: Prisma.ConvoyWhereInput | Prisma.ConvoyWhereInput[]
  OR?: Prisma.ConvoyWhereInput[]
  NOT?: Prisma.ConvoyWhereInput | Prisma.ConvoyWhereInput[]
  id?: Prisma.StringFilter<"Convoy"> | string
  status?: Prisma.EnumConvoyStatusFilter<"Convoy"> | $Enums.ConvoyStatus
  name?: Prisma.StringFilter<"Convoy"> | string
  accessCode?: Prisma.StringFilter<"Convoy"> | string
  organizerPasswordHash?: Prisma.StringFilter<"Convoy"> | string
  createdAt?: Prisma.DateTimeFilter<"Convoy"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Convoy"> | Date | string
  segments?: Prisma.ConvoySegmentListRelationFilter
}

export type ConvoyOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  status?: Prisma.SortOrder
  name?: Prisma.SortOrder
  accessCode?: Prisma.SortOrder
  organizerPasswordHash?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  segments?: Prisma.ConvoySegmentOrderByRelationAggregateInput
}

export type ConvoyWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  accessCode?: string
  organizerPasswordHash?: string
  AND?: Prisma.ConvoyWhereInput | Prisma.ConvoyWhereInput[]
  OR?: Prisma.ConvoyWhereInput[]
  NOT?: Prisma.ConvoyWhereInput | Prisma.ConvoyWhereInput[]
  status?: Prisma.EnumConvoyStatusFilter<"Convoy"> | $Enums.ConvoyStatus
  name?: Prisma.StringFilter<"Convoy"> | string
  createdAt?: Prisma.DateTimeFilter<"Convoy"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Convoy"> | Date | string
  segments?: Prisma.ConvoySegmentListRelationFilter
}, "id" | "accessCode" | "organizerPasswordHash">

export type ConvoyOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  status?: Prisma.SortOrder
  name?: Prisma.SortOrder
  accessCode?: Prisma.SortOrder
  organizerPasswordHash?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.ConvoyCountOrderByAggregateInput
  _max?: Prisma.ConvoyMaxOrderByAggregateInput
  _min?: Prisma.ConvoyMinOrderByAggregateInput
}

export type ConvoyScalarWhereWithAggregatesInput = {
  AND?: Prisma.ConvoyScalarWhereWithAggregatesInput | Prisma.ConvoyScalarWhereWithAggregatesInput[]
  OR?: Prisma.ConvoyScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ConvoyScalarWhereWithAggregatesInput | Prisma.ConvoyScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Convoy"> | string
  status?: Prisma.EnumConvoyStatusWithAggregatesFilter<"Convoy"> | $Enums.ConvoyStatus
  name?: Prisma.StringWithAggregatesFilter<"Convoy"> | string
  accessCode?: Prisma.StringWithAggregatesFilter<"Convoy"> | string
  organizerPasswordHash?: Prisma.StringWithAggregatesFilter<"Convoy"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Convoy"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Convoy"> | Date | string
}

export type ConvoyCreateInput = {
  id?: string
  status?: $Enums.ConvoyStatus
  name: string
  accessCode: string
  organizerPasswordHash: string
  createdAt?: Date | string
  updatedAt?: Date | string
  segments?: Prisma.ConvoySegmentCreateNestedManyWithoutConvoyInput
}

export type ConvoyUncheckedCreateInput = {
  id?: string
  status?: $Enums.ConvoyStatus
  name: string
  accessCode: string
  organizerPasswordHash: string
  createdAt?: Date | string
  updatedAt?: Date | string
  segments?: Prisma.ConvoySegmentUncheckedCreateNestedManyWithoutConvoyInput
}

export type ConvoyUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumConvoyStatusFieldUpdateOperationsInput | $Enums.ConvoyStatus
  name?: Prisma.StringFieldUpdateOperationsInput | string
  accessCode?: Prisma.StringFieldUpdateOperationsInput | string
  organizerPasswordHash?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  segments?: Prisma.ConvoySegmentUpdateManyWithoutConvoyNestedInput
}

export type ConvoyUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumConvoyStatusFieldUpdateOperationsInput | $Enums.ConvoyStatus
  name?: Prisma.StringFieldUpdateOperationsInput | string
  accessCode?: Prisma.StringFieldUpdateOperationsInput | string
  organizerPasswordHash?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  segments?: Prisma.ConvoySegmentUncheckedUpdateManyWithoutConvoyNestedInput
}

export type ConvoyCreateManyInput = {
  id?: string
  status?: $Enums.ConvoyStatus
  name: string
  accessCode: string
  organizerPasswordHash: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ConvoyUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumConvoyStatusFieldUpdateOperationsInput | $Enums.ConvoyStatus
  name?: Prisma.StringFieldUpdateOperationsInput | string
  accessCode?: Prisma.StringFieldUpdateOperationsInput | string
  organizerPasswordHash?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ConvoyUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumConvoyStatusFieldUpdateOperationsInput | $Enums.ConvoyStatus
  name?: Prisma.StringFieldUpdateOperationsInput | string
  accessCode?: Prisma.StringFieldUpdateOperationsInput | string
  organizerPasswordHash?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ConvoyCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  status?: Prisma.SortOrder
  name?: Prisma.SortOrder
  accessCode?: Prisma.SortOrder
  organizerPasswordHash?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ConvoyMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  status?: Prisma.SortOrder
  name?: Prisma.SortOrder
  accessCode?: Prisma.SortOrder
  organizerPasswordHash?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ConvoyMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  status?: Prisma.SortOrder
  name?: Prisma.SortOrder
  accessCode?: Prisma.SortOrder
  organizerPasswordHash?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ConvoyScalarRelationFilter = {
  is?: Prisma.ConvoyWhereInput
  isNot?: Prisma.ConvoyWhereInput
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type EnumConvoyStatusFieldUpdateOperationsInput = {
  set?: $Enums.ConvoyStatus
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type ConvoyCreateNestedOneWithoutSegmentsInput = {
  create?: Prisma.XOR<Prisma.ConvoyCreateWithoutSegmentsInput, Prisma.ConvoyUncheckedCreateWithoutSegmentsInput>
  connectOrCreate?: Prisma.ConvoyCreateOrConnectWithoutSegmentsInput
  connect?: Prisma.ConvoyWhereUniqueInput
}

export type ConvoyUpdateOneRequiredWithoutSegmentsNestedInput = {
  create?: Prisma.XOR<Prisma.ConvoyCreateWithoutSegmentsInput, Prisma.ConvoyUncheckedCreateWithoutSegmentsInput>
  connectOrCreate?: Prisma.ConvoyCreateOrConnectWithoutSegmentsInput
  upsert?: Prisma.ConvoyUpsertWithoutSegmentsInput
  connect?: Prisma.ConvoyWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ConvoyUpdateToOneWithWhereWithoutSegmentsInput, Prisma.ConvoyUpdateWithoutSegmentsInput>, Prisma.ConvoyUncheckedUpdateWithoutSegmentsInput>
}

export type ConvoyCreateWithoutSegmentsInput = {
  id?: string
  status?: $Enums.ConvoyStatus
  name: string
  accessCode: string
  organizerPasswordHash: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ConvoyUncheckedCreateWithoutSegmentsInput = {
  id?: string
  status?: $Enums.ConvoyStatus
  name: string
  accessCode: string
  organizerPasswordHash: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ConvoyCreateOrConnectWithoutSegmentsInput = {
  where: Prisma.ConvoyWhereUniqueInput
  create: Prisma.XOR<Prisma.ConvoyCreateWithoutSegmentsInput, Prisma.ConvoyUncheckedCreateWithoutSegmentsInput>
}

export type ConvoyUpsertWithoutSegmentsInput = {
  update: Prisma.XOR<Prisma.ConvoyUpdateWithoutSegmentsInput, Prisma.ConvoyUncheckedUpdateWithoutSegmentsInput>
  create: Prisma.XOR<Prisma.ConvoyCreateWithoutSegmentsInput, Prisma.ConvoyUncheckedCreateWithoutSegmentsInput>
  where?: Prisma.ConvoyWhereInput
}

export type ConvoyUpdateToOneWithWhereWithoutSegmentsInput = {
  where?: Prisma.ConvoyWhereInput
  data: Prisma.XOR<Prisma.ConvoyUpdateWithoutSegmentsInput, Prisma.ConvoyUncheckedUpdateWithoutSegmentsInput>
}

export type ConvoyUpdateWithoutSegmentsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumConvoyStatusFieldUpdateOperationsInput | $Enums.ConvoyStatus
  name?: Prisma.StringFieldUpdateOperationsInput | string
  accessCode?: Prisma.StringFieldUpdateOperationsInput | string
  organizerPasswordHash?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ConvoyUncheckedUpdateWithoutSegmentsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumConvoyStatusFieldUpdateOperationsInput | $Enums.ConvoyStatus
  name?: Prisma.StringFieldUpdateOperationsInput | string
  accessCode?: Prisma.StringFieldUpdateOperationsInput | string
  organizerPasswordHash?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type ConvoyCountOutputType
 */

export type ConvoyCountOutputType = {
  segments: number
}

export type ConvoyCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  segments?: boolean | ConvoyCountOutputTypeCountSegmentsArgs
}

/**
 * ConvoyCountOutputType without action
 */
export type ConvoyCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ConvoyCountOutputType
   */
  select?: Prisma.ConvoyCountOutputTypeSelect<ExtArgs> | null
}

/**
 * ConvoyCountOutputType without action
 */
export type ConvoyCountOutputTypeCountSegmentsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ConvoySegmentWhereInput
}


export type ConvoySelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  status?: boolean
  name?: boolean
  accessCode?: boolean
  organizerPasswordHash?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  segments?: boolean | Prisma.Convoy$segmentsArgs<ExtArgs>
  _count?: boolean | Prisma.ConvoyCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["convoy"]>

export type ConvoySelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  status?: boolean
  name?: boolean
  accessCode?: boolean
  organizerPasswordHash?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["convoy"]>

export type ConvoySelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  status?: boolean
  name?: boolean
  accessCode?: boolean
  organizerPasswordHash?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["convoy"]>

export type ConvoySelectScalar = {
  id?: boolean
  status?: boolean
  name?: boolean
  accessCode?: boolean
  organizerPasswordHash?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type ConvoyOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "status" | "name" | "accessCode" | "organizerPasswordHash" | "createdAt" | "updatedAt", ExtArgs["result"]["convoy"]>
export type ConvoyInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  segments?: boolean | Prisma.Convoy$segmentsArgs<ExtArgs>
  _count?: boolean | Prisma.ConvoyCountOutputTypeDefaultArgs<ExtArgs>
}
export type ConvoyIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type ConvoyIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $ConvoyPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Convoy"
  objects: {
    segments: Prisma.$ConvoySegmentPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    status: $Enums.ConvoyStatus
    name: string
    accessCode: string
    organizerPasswordHash: string
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["convoy"]>
  composites: {}
}

export type ConvoyGetPayload<S extends boolean | null | undefined | ConvoyDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ConvoyPayload, S>

export type ConvoyCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ConvoyFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ConvoyCountAggregateInputType | true
  }

export interface ConvoyDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Convoy'], meta: { name: 'Convoy' } }
  /**
   * Find zero or one Convoy that matches the filter.
   * @param {ConvoyFindUniqueArgs} args - Arguments to find a Convoy
   * @example
   * // Get one Convoy
   * const convoy = await prisma.convoy.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ConvoyFindUniqueArgs>(args: Prisma.SelectSubset<T, ConvoyFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ConvoyClient<runtime.Types.Result.GetResult<Prisma.$ConvoyPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Convoy that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ConvoyFindUniqueOrThrowArgs} args - Arguments to find a Convoy
   * @example
   * // Get one Convoy
   * const convoy = await prisma.convoy.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ConvoyFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ConvoyFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ConvoyClient<runtime.Types.Result.GetResult<Prisma.$ConvoyPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Convoy that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ConvoyFindFirstArgs} args - Arguments to find a Convoy
   * @example
   * // Get one Convoy
   * const convoy = await prisma.convoy.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ConvoyFindFirstArgs>(args?: Prisma.SelectSubset<T, ConvoyFindFirstArgs<ExtArgs>>): Prisma.Prisma__ConvoyClient<runtime.Types.Result.GetResult<Prisma.$ConvoyPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Convoy that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ConvoyFindFirstOrThrowArgs} args - Arguments to find a Convoy
   * @example
   * // Get one Convoy
   * const convoy = await prisma.convoy.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ConvoyFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ConvoyFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ConvoyClient<runtime.Types.Result.GetResult<Prisma.$ConvoyPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Convoys that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ConvoyFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Convoys
   * const convoys = await prisma.convoy.findMany()
   * 
   * // Get first 10 Convoys
   * const convoys = await prisma.convoy.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const convoyWithIdOnly = await prisma.convoy.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ConvoyFindManyArgs>(args?: Prisma.SelectSubset<T, ConvoyFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ConvoyPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Convoy.
   * @param {ConvoyCreateArgs} args - Arguments to create a Convoy.
   * @example
   * // Create one Convoy
   * const Convoy = await prisma.convoy.create({
   *   data: {
   *     // ... data to create a Convoy
   *   }
   * })
   * 
   */
  create<T extends ConvoyCreateArgs>(args: Prisma.SelectSubset<T, ConvoyCreateArgs<ExtArgs>>): Prisma.Prisma__ConvoyClient<runtime.Types.Result.GetResult<Prisma.$ConvoyPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Convoys.
   * @param {ConvoyCreateManyArgs} args - Arguments to create many Convoys.
   * @example
   * // Create many Convoys
   * const convoy = await prisma.convoy.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ConvoyCreateManyArgs>(args?: Prisma.SelectSubset<T, ConvoyCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Convoys and returns the data saved in the database.
   * @param {ConvoyCreateManyAndReturnArgs} args - Arguments to create many Convoys.
   * @example
   * // Create many Convoys
   * const convoy = await prisma.convoy.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Convoys and only return the `id`
   * const convoyWithIdOnly = await prisma.convoy.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ConvoyCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ConvoyCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ConvoyPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Convoy.
   * @param {ConvoyDeleteArgs} args - Arguments to delete one Convoy.
   * @example
   * // Delete one Convoy
   * const Convoy = await prisma.convoy.delete({
   *   where: {
   *     // ... filter to delete one Convoy
   *   }
   * })
   * 
   */
  delete<T extends ConvoyDeleteArgs>(args: Prisma.SelectSubset<T, ConvoyDeleteArgs<ExtArgs>>): Prisma.Prisma__ConvoyClient<runtime.Types.Result.GetResult<Prisma.$ConvoyPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Convoy.
   * @param {ConvoyUpdateArgs} args - Arguments to update one Convoy.
   * @example
   * // Update one Convoy
   * const convoy = await prisma.convoy.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ConvoyUpdateArgs>(args: Prisma.SelectSubset<T, ConvoyUpdateArgs<ExtArgs>>): Prisma.Prisma__ConvoyClient<runtime.Types.Result.GetResult<Prisma.$ConvoyPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Convoys.
   * @param {ConvoyDeleteManyArgs} args - Arguments to filter Convoys to delete.
   * @example
   * // Delete a few Convoys
   * const { count } = await prisma.convoy.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ConvoyDeleteManyArgs>(args?: Prisma.SelectSubset<T, ConvoyDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Convoys.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ConvoyUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Convoys
   * const convoy = await prisma.convoy.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ConvoyUpdateManyArgs>(args: Prisma.SelectSubset<T, ConvoyUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Convoys and returns the data updated in the database.
   * @param {ConvoyUpdateManyAndReturnArgs} args - Arguments to update many Convoys.
   * @example
   * // Update many Convoys
   * const convoy = await prisma.convoy.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Convoys and only return the `id`
   * const convoyWithIdOnly = await prisma.convoy.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ConvoyUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ConvoyUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ConvoyPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Convoy.
   * @param {ConvoyUpsertArgs} args - Arguments to update or create a Convoy.
   * @example
   * // Update or create a Convoy
   * const convoy = await prisma.convoy.upsert({
   *   create: {
   *     // ... data to create a Convoy
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Convoy we want to update
   *   }
   * })
   */
  upsert<T extends ConvoyUpsertArgs>(args: Prisma.SelectSubset<T, ConvoyUpsertArgs<ExtArgs>>): Prisma.Prisma__ConvoyClient<runtime.Types.Result.GetResult<Prisma.$ConvoyPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Convoys.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ConvoyCountArgs} args - Arguments to filter Convoys to count.
   * @example
   * // Count the number of Convoys
   * const count = await prisma.convoy.count({
   *   where: {
   *     // ... the filter for the Convoys we want to count
   *   }
   * })
  **/
  count<T extends ConvoyCountArgs>(
    args?: Prisma.Subset<T, ConvoyCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ConvoyCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Convoy.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ConvoyAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ConvoyAggregateArgs>(args: Prisma.Subset<T, ConvoyAggregateArgs>): Prisma.PrismaPromise<GetConvoyAggregateType<T>>

  /**
   * Group by Convoy.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ConvoyGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ConvoyGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ConvoyGroupByArgs['orderBy'] }
      : { orderBy?: ConvoyGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ConvoyGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetConvoyGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Convoy model
 */
readonly fields: ConvoyFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Convoy.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ConvoyClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  segments<T extends Prisma.Convoy$segmentsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Convoy$segmentsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ConvoySegmentPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Convoy model
 */
export interface ConvoyFieldRefs {
  readonly id: Prisma.FieldRef<"Convoy", 'String'>
  readonly status: Prisma.FieldRef<"Convoy", 'ConvoyStatus'>
  readonly name: Prisma.FieldRef<"Convoy", 'String'>
  readonly accessCode: Prisma.FieldRef<"Convoy", 'String'>
  readonly organizerPasswordHash: Prisma.FieldRef<"Convoy", 'String'>
  readonly createdAt: Prisma.FieldRef<"Convoy", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Convoy", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Convoy findUnique
 */
export type ConvoyFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Convoy
   */
  select?: Prisma.ConvoySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Convoy
   */
  omit?: Prisma.ConvoyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ConvoyInclude<ExtArgs> | null
  /**
   * Filter, which Convoy to fetch.
   */
  where: Prisma.ConvoyWhereUniqueInput
}

/**
 * Convoy findUniqueOrThrow
 */
export type ConvoyFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Convoy
   */
  select?: Prisma.ConvoySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Convoy
   */
  omit?: Prisma.ConvoyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ConvoyInclude<ExtArgs> | null
  /**
   * Filter, which Convoy to fetch.
   */
  where: Prisma.ConvoyWhereUniqueInput
}

/**
 * Convoy findFirst
 */
export type ConvoyFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Convoy
   */
  select?: Prisma.ConvoySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Convoy
   */
  omit?: Prisma.ConvoyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ConvoyInclude<ExtArgs> | null
  /**
   * Filter, which Convoy to fetch.
   */
  where?: Prisma.ConvoyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Convoys to fetch.
   */
  orderBy?: Prisma.ConvoyOrderByWithRelationInput | Prisma.ConvoyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Convoys.
   */
  cursor?: Prisma.ConvoyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Convoys from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Convoys.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Convoys.
   */
  distinct?: Prisma.ConvoyScalarFieldEnum | Prisma.ConvoyScalarFieldEnum[]
}

/**
 * Convoy findFirstOrThrow
 */
export type ConvoyFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Convoy
   */
  select?: Prisma.ConvoySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Convoy
   */
  omit?: Prisma.ConvoyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ConvoyInclude<ExtArgs> | null
  /**
   * Filter, which Convoy to fetch.
   */
  where?: Prisma.ConvoyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Convoys to fetch.
   */
  orderBy?: Prisma.ConvoyOrderByWithRelationInput | Prisma.ConvoyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Convoys.
   */
  cursor?: Prisma.ConvoyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Convoys from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Convoys.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Convoys.
   */
  distinct?: Prisma.ConvoyScalarFieldEnum | Prisma.ConvoyScalarFieldEnum[]
}

/**
 * Convoy findMany
 */
export type ConvoyFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Convoy
   */
  select?: Prisma.ConvoySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Convoy
   */
  omit?: Prisma.ConvoyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ConvoyInclude<ExtArgs> | null
  /**
   * Filter, which Convoys to fetch.
   */
  where?: Prisma.ConvoyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Convoys to fetch.
   */
  orderBy?: Prisma.ConvoyOrderByWithRelationInput | Prisma.ConvoyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Convoys.
   */
  cursor?: Prisma.ConvoyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Convoys from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Convoys.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Convoys.
   */
  distinct?: Prisma.ConvoyScalarFieldEnum | Prisma.ConvoyScalarFieldEnum[]
}

/**
 * Convoy create
 */
export type ConvoyCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Convoy
   */
  select?: Prisma.ConvoySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Convoy
   */
  omit?: Prisma.ConvoyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ConvoyInclude<ExtArgs> | null
  /**
   * The data needed to create a Convoy.
   */
  data: Prisma.XOR<Prisma.ConvoyCreateInput, Prisma.ConvoyUncheckedCreateInput>
}

/**
 * Convoy createMany
 */
export type ConvoyCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Convoys.
   */
  data: Prisma.ConvoyCreateManyInput | Prisma.ConvoyCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Convoy createManyAndReturn
 */
export type ConvoyCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Convoy
   */
  select?: Prisma.ConvoySelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Convoy
   */
  omit?: Prisma.ConvoyOmit<ExtArgs> | null
  /**
   * The data used to create many Convoys.
   */
  data: Prisma.ConvoyCreateManyInput | Prisma.ConvoyCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Convoy update
 */
export type ConvoyUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Convoy
   */
  select?: Prisma.ConvoySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Convoy
   */
  omit?: Prisma.ConvoyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ConvoyInclude<ExtArgs> | null
  /**
   * The data needed to update a Convoy.
   */
  data: Prisma.XOR<Prisma.ConvoyUpdateInput, Prisma.ConvoyUncheckedUpdateInput>
  /**
   * Choose, which Convoy to update.
   */
  where: Prisma.ConvoyWhereUniqueInput
}

/**
 * Convoy updateMany
 */
export type ConvoyUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Convoys.
   */
  data: Prisma.XOR<Prisma.ConvoyUpdateManyMutationInput, Prisma.ConvoyUncheckedUpdateManyInput>
  /**
   * Filter which Convoys to update
   */
  where?: Prisma.ConvoyWhereInput
  /**
   * Limit how many Convoys to update.
   */
  limit?: number
}

/**
 * Convoy updateManyAndReturn
 */
export type ConvoyUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Convoy
   */
  select?: Prisma.ConvoySelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Convoy
   */
  omit?: Prisma.ConvoyOmit<ExtArgs> | null
  /**
   * The data used to update Convoys.
   */
  data: Prisma.XOR<Prisma.ConvoyUpdateManyMutationInput, Prisma.ConvoyUncheckedUpdateManyInput>
  /**
   * Filter which Convoys to update
   */
  where?: Prisma.ConvoyWhereInput
  /**
   * Limit how many Convoys to update.
   */
  limit?: number
}

/**
 * Convoy upsert
 */
export type ConvoyUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Convoy
   */
  select?: Prisma.ConvoySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Convoy
   */
  omit?: Prisma.ConvoyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ConvoyInclude<ExtArgs> | null
  /**
   * The filter to search for the Convoy to update in case it exists.
   */
  where: Prisma.ConvoyWhereUniqueInput
  /**
   * In case the Convoy found by the `where` argument doesn't exist, create a new Convoy with this data.
   */
  create: Prisma.XOR<Prisma.ConvoyCreateInput, Prisma.ConvoyUncheckedCreateInput>
  /**
   * In case the Convoy was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ConvoyUpdateInput, Prisma.ConvoyUncheckedUpdateInput>
}

/**
 * Convoy delete
 */
export type ConvoyDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Convoy
   */
  select?: Prisma.ConvoySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Convoy
   */
  omit?: Prisma.ConvoyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ConvoyInclude<ExtArgs> | null
  /**
   * Filter which Convoy to delete.
   */
  where: Prisma.ConvoyWhereUniqueInput
}

/**
 * Convoy deleteMany
 */
export type ConvoyDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Convoys to delete
   */
  where?: Prisma.ConvoyWhereInput
  /**
   * Limit how many Convoys to delete.
   */
  limit?: number
}

/**
 * Convoy.segments
 */
export type Convoy$segmentsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ConvoySegment
   */
  select?: Prisma.ConvoySegmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ConvoySegment
   */
  omit?: Prisma.ConvoySegmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ConvoySegmentInclude<ExtArgs> | null
  where?: Prisma.ConvoySegmentWhereInput
  orderBy?: Prisma.ConvoySegmentOrderByWithRelationInput | Prisma.ConvoySegmentOrderByWithRelationInput[]
  cursor?: Prisma.ConvoySegmentWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ConvoySegmentScalarFieldEnum | Prisma.ConvoySegmentScalarFieldEnum[]
}

/**
 * Convoy without action
 */
export type ConvoyDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Convoy
   */
  select?: Prisma.ConvoySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Convoy
   */
  omit?: Prisma.ConvoyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ConvoyInclude<ExtArgs> | null
}
