
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ConvoyPOI` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model ConvoyPOI
 * 
 */
export type ConvoyPOIModel = runtime.Types.Result.DefaultSelection<Prisma.$ConvoyPOIPayload>

export type AggregateConvoyPOI = {
  _count: ConvoyPOICountAggregateOutputType | null
  _avg: ConvoyPOIAvgAggregateOutputType | null
  _sum: ConvoyPOISumAggregateOutputType | null
  _min: ConvoyPOIMinAggregateOutputType | null
  _max: ConvoyPOIMaxAggregateOutputType | null
}

export type ConvoyPOIAvgAggregateOutputType = {
  lat: number | null
  lon: number | null
}

export type ConvoyPOISumAggregateOutputType = {
  lat: number | null
  lon: number | null
}

export type ConvoyPOIMinAggregateOutputType = {
  id: string | null
  segmentId: string | null
  label: string | null
  lat: number | null
  lon: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ConvoyPOIMaxAggregateOutputType = {
  id: string | null
  segmentId: string | null
  label: string | null
  lat: number | null
  lon: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ConvoyPOICountAggregateOutputType = {
  id: number
  segmentId: number
  label: number
  lat: number
  lon: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type ConvoyPOIAvgAggregateInputType = {
  lat?: true
  lon?: true
}

export type ConvoyPOISumAggregateInputType = {
  lat?: true
  lon?: true
}

export type ConvoyPOIMinAggregateInputType = {
  id?: true
  segmentId?: true
  label?: true
  lat?: true
  lon?: true
  createdAt?: true
  updatedAt?: true
}

export type ConvoyPOIMaxAggregateInputType = {
  id?: true
  segmentId?: true
  label?: true
  lat?: true
  lon?: true
  createdAt?: true
  updatedAt?: true
}

export type ConvoyPOICountAggregateInputType = {
  id?: true
  segmentId?: true
  label?: true
  lat?: true
  lon?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type ConvoyPOIAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ConvoyPOI to aggregate.
   */
  where?: Prisma.ConvoyPOIWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ConvoyPOIS to fetch.
   */
  orderBy?: Prisma.ConvoyPOIOrderByWithRelationInput | Prisma.ConvoyPOIOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ConvoyPOIWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ConvoyPOIS from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ConvoyPOIS.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ConvoyPOIS
  **/
  _count?: true | ConvoyPOICountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ConvoyPOIAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ConvoyPOISumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ConvoyPOIMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ConvoyPOIMaxAggregateInputType
}

export type GetConvoyPOIAggregateType<T extends ConvoyPOIAggregateArgs> = {
      [P in keyof T & keyof AggregateConvoyPOI]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateConvoyPOI[P]>
    : Prisma.GetScalarType<T[P], AggregateConvoyPOI[P]>
}




export type ConvoyPOIGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ConvoyPOIWhereInput
  orderBy?: Prisma.ConvoyPOIOrderByWithAggregationInput | Prisma.ConvoyPOIOrderByWithAggregationInput[]
  by: Prisma.ConvoyPOIScalarFieldEnum[] | Prisma.ConvoyPOIScalarFieldEnum
  having?: Prisma.ConvoyPOIScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ConvoyPOICountAggregateInputType | true
  _avg?: ConvoyPOIAvgAggregateInputType
  _sum?: ConvoyPOISumAggregateInputType
  _min?: ConvoyPOIMinAggregateInputType
  _max?: ConvoyPOIMaxAggregateInputType
}

export type ConvoyPOIGroupByOutputType = {
  id: string
  segmentId: string
  label: string
  lat: number
  lon: number
  createdAt: Date
  updatedAt: Date
  _count: ConvoyPOICountAggregateOutputType | null
  _avg: ConvoyPOIAvgAggregateOutputType | null
  _sum: ConvoyPOISumAggregateOutputType | null
  _min: ConvoyPOIMinAggregateOutputType | null
  _max: ConvoyPOIMaxAggregateOutputType | null
}

export type GetConvoyPOIGroupByPayload<T extends ConvoyPOIGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ConvoyPOIGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ConvoyPOIGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ConvoyPOIGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ConvoyPOIGroupByOutputType[P]>
      }
    >
  >



export type ConvoyPOIWhereInput = {
  AND?: Prisma.ConvoyPOIWhereInput | Prisma.ConvoyPOIWhereInput[]
  OR?: Prisma.ConvoyPOIWhereInput[]
  NOT?: Prisma.ConvoyPOIWhereInput | Prisma.ConvoyPOIWhereInput[]
  id?: Prisma.StringFilter<"ConvoyPOI"> | string
  segmentId?: Prisma.StringFilter<"ConvoyPOI"> | string
  label?: Prisma.StringFilter<"ConvoyPOI"> | string
  lat?: Prisma.FloatFilter<"ConvoyPOI"> | number
  lon?: Prisma.FloatFilter<"ConvoyPOI"> | number
  createdAt?: Prisma.DateTimeFilter<"ConvoyPOI"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ConvoyPOI"> | Date | string
  segment?: Prisma.XOR<Prisma.ConvoySegmentScalarRelationFilter, Prisma.ConvoySegmentWhereInput>
}

export type ConvoyPOIOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  segmentId?: Prisma.SortOrder
  label?: Prisma.SortOrder
  lat?: Prisma.SortOrder
  lon?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  segment?: Prisma.ConvoySegmentOrderByWithRelationInput
}

export type ConvoyPOIWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  segmentId?: string
  AND?: Prisma.ConvoyPOIWhereInput | Prisma.ConvoyPOIWhereInput[]
  OR?: Prisma.ConvoyPOIWhereInput[]
  NOT?: Prisma.ConvoyPOIWhereInput | Prisma.ConvoyPOIWhereInput[]
  label?: Prisma.StringFilter<"ConvoyPOI"> | string
  lat?: Prisma.FloatFilter<"ConvoyPOI"> | number
  lon?: Prisma.FloatFilter<"ConvoyPOI"> | number
  createdAt?: Prisma.DateTimeFilter<"ConvoyPOI"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ConvoyPOI"> | Date | string
  segment?: Prisma.XOR<Prisma.ConvoySegmentScalarRelationFilter, Prisma.ConvoySegmentWhereInput>
}, "id" | "segmentId">

export type ConvoyPOIOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  segmentId?: Prisma.SortOrder
  label?: Prisma.SortOrder
  lat?: Prisma.SortOrder
  lon?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.ConvoyPOICountOrderByAggregateInput
  _avg?: Prisma.ConvoyPOIAvgOrderByAggregateInput
  _max?: Prisma.ConvoyPOIMaxOrderByAggregateInput
  _min?: Prisma.ConvoyPOIMinOrderByAggregateInput
  _sum?: Prisma.ConvoyPOISumOrderByAggregateInput
}

export type ConvoyPOIScalarWhereWithAggregatesInput = {
  AND?: Prisma.ConvoyPOIScalarWhereWithAggregatesInput | Prisma.ConvoyPOIScalarWhereWithAggregatesInput[]
  OR?: Prisma.ConvoyPOIScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ConvoyPOIScalarWhereWithAggregatesInput | Prisma.ConvoyPOIScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ConvoyPOI"> | string
  segmentId?: Prisma.StringWithAggregatesFilter<"ConvoyPOI"> | string
  label?: Prisma.StringWithAggregatesFilter<"ConvoyPOI"> | string
  lat?: Prisma.FloatWithAggregatesFilter<"ConvoyPOI"> | number
  lon?: Prisma.FloatWithAggregatesFilter<"ConvoyPOI"> | number
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"ConvoyPOI"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"ConvoyPOI"> | Date | string
}

export type ConvoyPOICreateInput = {
  id?: string
  label: string
  lat: number
  lon: number
  createdAt?: Date | string
  updatedAt?: Date | string
  segment: Prisma.ConvoySegmentCreateNestedOneWithoutPoiInput
}

export type ConvoyPOIUncheckedCreateInput = {
  id?: string
  segmentId: string
  label: string
  lat: number
  lon: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ConvoyPOIUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  lat?: Prisma.FloatFieldUpdateOperationsInput | number
  lon?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  segment?: Prisma.ConvoySegmentUpdateOneRequiredWithoutPoiNestedInput
}

export type ConvoyPOIUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  segmentId?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  lat?: Prisma.FloatFieldUpdateOperationsInput | number
  lon?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ConvoyPOICreateManyInput = {
  id?: string
  segmentId: string
  label: string
  lat: number
  lon: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ConvoyPOIUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  lat?: Prisma.FloatFieldUpdateOperationsInput | number
  lon?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ConvoyPOIUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  segmentId?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  lat?: Prisma.FloatFieldUpdateOperationsInput | number
  lon?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ConvoyPOINullableScalarRelationFilter = {
  is?: Prisma.ConvoyPOIWhereInput | null
  isNot?: Prisma.ConvoyPOIWhereInput | null
}

export type ConvoyPOICountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  segmentId?: Prisma.SortOrder
  label?: Prisma.SortOrder
  lat?: Prisma.SortOrder
  lon?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ConvoyPOIAvgOrderByAggregateInput = {
  lat?: Prisma.SortOrder
  lon?: Prisma.SortOrder
}

export type ConvoyPOIMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  segmentId?: Prisma.SortOrder
  label?: Prisma.SortOrder
  lat?: Prisma.SortOrder
  lon?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ConvoyPOIMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  segmentId?: Prisma.SortOrder
  label?: Prisma.SortOrder
  lat?: Prisma.SortOrder
  lon?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ConvoyPOISumOrderByAggregateInput = {
  lat?: Prisma.SortOrder
  lon?: Prisma.SortOrder
}

export type ConvoyPOICreateNestedOneWithoutSegmentInput = {
  create?: Prisma.XOR<Prisma.ConvoyPOICreateWithoutSegmentInput, Prisma.ConvoyPOIUncheckedCreateWithoutSegmentInput>
  connectOrCreate?: Prisma.ConvoyPOICreateOrConnectWithoutSegmentInput
  connect?: Prisma.ConvoyPOIWhereUniqueInput
}

export type ConvoyPOIUncheckedCreateNestedOneWithoutSegmentInput = {
  create?: Prisma.XOR<Prisma.ConvoyPOICreateWithoutSegmentInput, Prisma.ConvoyPOIUncheckedCreateWithoutSegmentInput>
  connectOrCreate?: Prisma.ConvoyPOICreateOrConnectWithoutSegmentInput
  connect?: Prisma.ConvoyPOIWhereUniqueInput
}

export type ConvoyPOIUpdateOneWithoutSegmentNestedInput = {
  create?: Prisma.XOR<Prisma.ConvoyPOICreateWithoutSegmentInput, Prisma.ConvoyPOIUncheckedCreateWithoutSegmentInput>
  connectOrCreate?: Prisma.ConvoyPOICreateOrConnectWithoutSegmentInput
  upsert?: Prisma.ConvoyPOIUpsertWithoutSegmentInput
  disconnect?: Prisma.ConvoyPOIWhereInput | boolean
  delete?: Prisma.ConvoyPOIWhereInput | boolean
  connect?: Prisma.ConvoyPOIWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ConvoyPOIUpdateToOneWithWhereWithoutSegmentInput, Prisma.ConvoyPOIUpdateWithoutSegmentInput>, Prisma.ConvoyPOIUncheckedUpdateWithoutSegmentInput>
}

export type ConvoyPOIUncheckedUpdateOneWithoutSegmentNestedInput = {
  create?: Prisma.XOR<Prisma.ConvoyPOICreateWithoutSegmentInput, Prisma.ConvoyPOIUncheckedCreateWithoutSegmentInput>
  connectOrCreate?: Prisma.ConvoyPOICreateOrConnectWithoutSegmentInput
  upsert?: Prisma.ConvoyPOIUpsertWithoutSegmentInput
  disconnect?: Prisma.ConvoyPOIWhereInput | boolean
  delete?: Prisma.ConvoyPOIWhereInput | boolean
  connect?: Prisma.ConvoyPOIWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ConvoyPOIUpdateToOneWithWhereWithoutSegmentInput, Prisma.ConvoyPOIUpdateWithoutSegmentInput>, Prisma.ConvoyPOIUncheckedUpdateWithoutSegmentInput>
}

export type ConvoyPOICreateWithoutSegmentInput = {
  id?: string
  label: string
  lat: number
  lon: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ConvoyPOIUncheckedCreateWithoutSegmentInput = {
  id?: string
  label: string
  lat: number
  lon: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ConvoyPOICreateOrConnectWithoutSegmentInput = {
  where: Prisma.ConvoyPOIWhereUniqueInput
  create: Prisma.XOR<Prisma.ConvoyPOICreateWithoutSegmentInput, Prisma.ConvoyPOIUncheckedCreateWithoutSegmentInput>
}

export type ConvoyPOIUpsertWithoutSegmentInput = {
  update: Prisma.XOR<Prisma.ConvoyPOIUpdateWithoutSegmentInput, Prisma.ConvoyPOIUncheckedUpdateWithoutSegmentInput>
  create: Prisma.XOR<Prisma.ConvoyPOICreateWithoutSegmentInput, Prisma.ConvoyPOIUncheckedCreateWithoutSegmentInput>
  where?: Prisma.ConvoyPOIWhereInput
}

export type ConvoyPOIUpdateToOneWithWhereWithoutSegmentInput = {
  where?: Prisma.ConvoyPOIWhereInput
  data: Prisma.XOR<Prisma.ConvoyPOIUpdateWithoutSegmentInput, Prisma.ConvoyPOIUncheckedUpdateWithoutSegmentInput>
}

export type ConvoyPOIUpdateWithoutSegmentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  lat?: Prisma.FloatFieldUpdateOperationsInput | number
  lon?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ConvoyPOIUncheckedUpdateWithoutSegmentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  lat?: Prisma.FloatFieldUpdateOperationsInput | number
  lon?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type ConvoyPOISelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  segmentId?: boolean
  label?: boolean
  lat?: boolean
  lon?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  segment?: boolean | Prisma.ConvoySegmentDefaultArgs<ExtArgs>
}, ExtArgs["result"]["convoyPOI"]>

export type ConvoyPOISelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  segmentId?: boolean
  label?: boolean
  lat?: boolean
  lon?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  segment?: boolean | Prisma.ConvoySegmentDefaultArgs<ExtArgs>
}, ExtArgs["result"]["convoyPOI"]>

export type ConvoyPOISelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  segmentId?: boolean
  label?: boolean
  lat?: boolean
  lon?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  segment?: boolean | Prisma.ConvoySegmentDefaultArgs<ExtArgs>
}, ExtArgs["result"]["convoyPOI"]>

export type ConvoyPOISelectScalar = {
  id?: boolean
  segmentId?: boolean
  label?: boolean
  lat?: boolean
  lon?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type ConvoyPOIOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "segmentId" | "label" | "lat" | "lon" | "createdAt" | "updatedAt", ExtArgs["result"]["convoyPOI"]>
export type ConvoyPOIInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  segment?: boolean | Prisma.ConvoySegmentDefaultArgs<ExtArgs>
}
export type ConvoyPOIIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  segment?: boolean | Prisma.ConvoySegmentDefaultArgs<ExtArgs>
}
export type ConvoyPOIIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  segment?: boolean | Prisma.ConvoySegmentDefaultArgs<ExtArgs>
}

export type $ConvoyPOIPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ConvoyPOI"
  objects: {
    segment: Prisma.$ConvoySegmentPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    segmentId: string
    label: string
    lat: number
    lon: number
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["convoyPOI"]>
  composites: {}
}

export type ConvoyPOIGetPayload<S extends boolean | null | undefined | ConvoyPOIDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ConvoyPOIPayload, S>

export type ConvoyPOICountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ConvoyPOIFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ConvoyPOICountAggregateInputType | true
  }

export interface ConvoyPOIDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ConvoyPOI'], meta: { name: 'ConvoyPOI' } }
  /**
   * Find zero or one ConvoyPOI that matches the filter.
   * @param {ConvoyPOIFindUniqueArgs} args - Arguments to find a ConvoyPOI
   * @example
   * // Get one ConvoyPOI
   * const convoyPOI = await prisma.convoyPOI.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ConvoyPOIFindUniqueArgs>(args: Prisma.SelectSubset<T, ConvoyPOIFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ConvoyPOIClient<runtime.Types.Result.GetResult<Prisma.$ConvoyPOIPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ConvoyPOI that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ConvoyPOIFindUniqueOrThrowArgs} args - Arguments to find a ConvoyPOI
   * @example
   * // Get one ConvoyPOI
   * const convoyPOI = await prisma.convoyPOI.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ConvoyPOIFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ConvoyPOIFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ConvoyPOIClient<runtime.Types.Result.GetResult<Prisma.$ConvoyPOIPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ConvoyPOI that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ConvoyPOIFindFirstArgs} args - Arguments to find a ConvoyPOI
   * @example
   * // Get one ConvoyPOI
   * const convoyPOI = await prisma.convoyPOI.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ConvoyPOIFindFirstArgs>(args?: Prisma.SelectSubset<T, ConvoyPOIFindFirstArgs<ExtArgs>>): Prisma.Prisma__ConvoyPOIClient<runtime.Types.Result.GetResult<Prisma.$ConvoyPOIPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ConvoyPOI that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ConvoyPOIFindFirstOrThrowArgs} args - Arguments to find a ConvoyPOI
   * @example
   * // Get one ConvoyPOI
   * const convoyPOI = await prisma.convoyPOI.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ConvoyPOIFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ConvoyPOIFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ConvoyPOIClient<runtime.Types.Result.GetResult<Prisma.$ConvoyPOIPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ConvoyPOIS that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ConvoyPOIFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ConvoyPOIS
   * const convoyPOIS = await prisma.convoyPOI.findMany()
   * 
   * // Get first 10 ConvoyPOIS
   * const convoyPOIS = await prisma.convoyPOI.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const convoyPOIWithIdOnly = await prisma.convoyPOI.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ConvoyPOIFindManyArgs>(args?: Prisma.SelectSubset<T, ConvoyPOIFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ConvoyPOIPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ConvoyPOI.
   * @param {ConvoyPOICreateArgs} args - Arguments to create a ConvoyPOI.
   * @example
   * // Create one ConvoyPOI
   * const ConvoyPOI = await prisma.convoyPOI.create({
   *   data: {
   *     // ... data to create a ConvoyPOI
   *   }
   * })
   * 
   */
  create<T extends ConvoyPOICreateArgs>(args: Prisma.SelectSubset<T, ConvoyPOICreateArgs<ExtArgs>>): Prisma.Prisma__ConvoyPOIClient<runtime.Types.Result.GetResult<Prisma.$ConvoyPOIPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ConvoyPOIS.
   * @param {ConvoyPOICreateManyArgs} args - Arguments to create many ConvoyPOIS.
   * @example
   * // Create many ConvoyPOIS
   * const convoyPOI = await prisma.convoyPOI.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ConvoyPOICreateManyArgs>(args?: Prisma.SelectSubset<T, ConvoyPOICreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ConvoyPOIS and returns the data saved in the database.
   * @param {ConvoyPOICreateManyAndReturnArgs} args - Arguments to create many ConvoyPOIS.
   * @example
   * // Create many ConvoyPOIS
   * const convoyPOI = await prisma.convoyPOI.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ConvoyPOIS and only return the `id`
   * const convoyPOIWithIdOnly = await prisma.convoyPOI.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ConvoyPOICreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ConvoyPOICreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ConvoyPOIPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ConvoyPOI.
   * @param {ConvoyPOIDeleteArgs} args - Arguments to delete one ConvoyPOI.
   * @example
   * // Delete one ConvoyPOI
   * const ConvoyPOI = await prisma.convoyPOI.delete({
   *   where: {
   *     // ... filter to delete one ConvoyPOI
   *   }
   * })
   * 
   */
  delete<T extends ConvoyPOIDeleteArgs>(args: Prisma.SelectSubset<T, ConvoyPOIDeleteArgs<ExtArgs>>): Prisma.Prisma__ConvoyPOIClient<runtime.Types.Result.GetResult<Prisma.$ConvoyPOIPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ConvoyPOI.
   * @param {ConvoyPOIUpdateArgs} args - Arguments to update one ConvoyPOI.
   * @example
   * // Update one ConvoyPOI
   * const convoyPOI = await prisma.convoyPOI.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ConvoyPOIUpdateArgs>(args: Prisma.SelectSubset<T, ConvoyPOIUpdateArgs<ExtArgs>>): Prisma.Prisma__ConvoyPOIClient<runtime.Types.Result.GetResult<Prisma.$ConvoyPOIPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ConvoyPOIS.
   * @param {ConvoyPOIDeleteManyArgs} args - Arguments to filter ConvoyPOIS to delete.
   * @example
   * // Delete a few ConvoyPOIS
   * const { count } = await prisma.convoyPOI.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ConvoyPOIDeleteManyArgs>(args?: Prisma.SelectSubset<T, ConvoyPOIDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ConvoyPOIS.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ConvoyPOIUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ConvoyPOIS
   * const convoyPOI = await prisma.convoyPOI.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ConvoyPOIUpdateManyArgs>(args: Prisma.SelectSubset<T, ConvoyPOIUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ConvoyPOIS and returns the data updated in the database.
   * @param {ConvoyPOIUpdateManyAndReturnArgs} args - Arguments to update many ConvoyPOIS.
   * @example
   * // Update many ConvoyPOIS
   * const convoyPOI = await prisma.convoyPOI.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ConvoyPOIS and only return the `id`
   * const convoyPOIWithIdOnly = await prisma.convoyPOI.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ConvoyPOIUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ConvoyPOIUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ConvoyPOIPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ConvoyPOI.
   * @param {ConvoyPOIUpsertArgs} args - Arguments to update or create a ConvoyPOI.
   * @example
   * // Update or create a ConvoyPOI
   * const convoyPOI = await prisma.convoyPOI.upsert({
   *   create: {
   *     // ... data to create a ConvoyPOI
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ConvoyPOI we want to update
   *   }
   * })
   */
  upsert<T extends ConvoyPOIUpsertArgs>(args: Prisma.SelectSubset<T, ConvoyPOIUpsertArgs<ExtArgs>>): Prisma.Prisma__ConvoyPOIClient<runtime.Types.Result.GetResult<Prisma.$ConvoyPOIPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ConvoyPOIS.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ConvoyPOICountArgs} args - Arguments to filter ConvoyPOIS to count.
   * @example
   * // Count the number of ConvoyPOIS
   * const count = await prisma.convoyPOI.count({
   *   where: {
   *     // ... the filter for the ConvoyPOIS we want to count
   *   }
   * })
  **/
  count<T extends ConvoyPOICountArgs>(
    args?: Prisma.Subset<T, ConvoyPOICountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ConvoyPOICountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ConvoyPOI.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ConvoyPOIAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ConvoyPOIAggregateArgs>(args: Prisma.Subset<T, ConvoyPOIAggregateArgs>): Prisma.PrismaPromise<GetConvoyPOIAggregateType<T>>

  /**
   * Group by ConvoyPOI.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ConvoyPOIGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ConvoyPOIGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ConvoyPOIGroupByArgs['orderBy'] }
      : { orderBy?: ConvoyPOIGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ConvoyPOIGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetConvoyPOIGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ConvoyPOI model
 */
readonly fields: ConvoyPOIFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ConvoyPOI.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ConvoyPOIClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  segment<T extends Prisma.ConvoySegmentDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ConvoySegmentDefaultArgs<ExtArgs>>): Prisma.Prisma__ConvoySegmentClient<runtime.Types.Result.GetResult<Prisma.$ConvoySegmentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ConvoyPOI model
 */
export interface ConvoyPOIFieldRefs {
  readonly id: Prisma.FieldRef<"ConvoyPOI", 'String'>
  readonly segmentId: Prisma.FieldRef<"ConvoyPOI", 'String'>
  readonly label: Prisma.FieldRef<"ConvoyPOI", 'String'>
  readonly lat: Prisma.FieldRef<"ConvoyPOI", 'Float'>
  readonly lon: Prisma.FieldRef<"ConvoyPOI", 'Float'>
  readonly createdAt: Prisma.FieldRef<"ConvoyPOI", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"ConvoyPOI", 'DateTime'>
}
    

// Custom InputTypes
/**
 * ConvoyPOI findUnique
 */
export type ConvoyPOIFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ConvoyPOI
   */
  select?: Prisma.ConvoyPOISelect<ExtArgs> | null
  /**
   * Omit specific fields from the ConvoyPOI
   */
  omit?: Prisma.ConvoyPOIOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ConvoyPOIInclude<ExtArgs> | null
  /**
   * Filter, which ConvoyPOI to fetch.
   */
  where: Prisma.ConvoyPOIWhereUniqueInput
}

/**
 * ConvoyPOI findUniqueOrThrow
 */
export type ConvoyPOIFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ConvoyPOI
   */
  select?: Prisma.ConvoyPOISelect<ExtArgs> | null
  /**
   * Omit specific fields from the ConvoyPOI
   */
  omit?: Prisma.ConvoyPOIOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ConvoyPOIInclude<ExtArgs> | null
  /**
   * Filter, which ConvoyPOI to fetch.
   */
  where: Prisma.ConvoyPOIWhereUniqueInput
}

/**
 * ConvoyPOI findFirst
 */
export type ConvoyPOIFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ConvoyPOI
   */
  select?: Prisma.ConvoyPOISelect<ExtArgs> | null
  /**
   * Omit specific fields from the ConvoyPOI
   */
  omit?: Prisma.ConvoyPOIOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ConvoyPOIInclude<ExtArgs> | null
  /**
   * Filter, which ConvoyPOI to fetch.
   */
  where?: Prisma.ConvoyPOIWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ConvoyPOIS to fetch.
   */
  orderBy?: Prisma.ConvoyPOIOrderByWithRelationInput | Prisma.ConvoyPOIOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ConvoyPOIS.
   */
  cursor?: Prisma.ConvoyPOIWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ConvoyPOIS from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ConvoyPOIS.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ConvoyPOIS.
   */
  distinct?: Prisma.ConvoyPOIScalarFieldEnum | Prisma.ConvoyPOIScalarFieldEnum[]
}

/**
 * ConvoyPOI findFirstOrThrow
 */
export type ConvoyPOIFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ConvoyPOI
   */
  select?: Prisma.ConvoyPOISelect<ExtArgs> | null
  /**
   * Omit specific fields from the ConvoyPOI
   */
  omit?: Prisma.ConvoyPOIOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ConvoyPOIInclude<ExtArgs> | null
  /**
   * Filter, which ConvoyPOI to fetch.
   */
  where?: Prisma.ConvoyPOIWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ConvoyPOIS to fetch.
   */
  orderBy?: Prisma.ConvoyPOIOrderByWithRelationInput | Prisma.ConvoyPOIOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ConvoyPOIS.
   */
  cursor?: Prisma.ConvoyPOIWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ConvoyPOIS from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ConvoyPOIS.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ConvoyPOIS.
   */
  distinct?: Prisma.ConvoyPOIScalarFieldEnum | Prisma.ConvoyPOIScalarFieldEnum[]
}

/**
 * ConvoyPOI findMany
 */
export type ConvoyPOIFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ConvoyPOI
   */
  select?: Prisma.ConvoyPOISelect<ExtArgs> | null
  /**
   * Omit specific fields from the ConvoyPOI
   */
  omit?: Prisma.ConvoyPOIOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ConvoyPOIInclude<ExtArgs> | null
  /**
   * Filter, which ConvoyPOIS to fetch.
   */
  where?: Prisma.ConvoyPOIWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ConvoyPOIS to fetch.
   */
  orderBy?: Prisma.ConvoyPOIOrderByWithRelationInput | Prisma.ConvoyPOIOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ConvoyPOIS.
   */
  cursor?: Prisma.ConvoyPOIWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ConvoyPOIS from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ConvoyPOIS.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ConvoyPOIS.
   */
  distinct?: Prisma.ConvoyPOIScalarFieldEnum | Prisma.ConvoyPOIScalarFieldEnum[]
}

/**
 * ConvoyPOI create
 */
export type ConvoyPOICreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ConvoyPOI
   */
  select?: Prisma.ConvoyPOISelect<ExtArgs> | null
  /**
   * Omit specific fields from the ConvoyPOI
   */
  omit?: Prisma.ConvoyPOIOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ConvoyPOIInclude<ExtArgs> | null
  /**
   * The data needed to create a ConvoyPOI.
   */
  data: Prisma.XOR<Prisma.ConvoyPOICreateInput, Prisma.ConvoyPOIUncheckedCreateInput>
}

/**
 * ConvoyPOI createMany
 */
export type ConvoyPOICreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ConvoyPOIS.
   */
  data: Prisma.ConvoyPOICreateManyInput | Prisma.ConvoyPOICreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ConvoyPOI createManyAndReturn
 */
export type ConvoyPOICreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ConvoyPOI
   */
  select?: Prisma.ConvoyPOISelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ConvoyPOI
   */
  omit?: Prisma.ConvoyPOIOmit<ExtArgs> | null
  /**
   * The data used to create many ConvoyPOIS.
   */
  data: Prisma.ConvoyPOICreateManyInput | Prisma.ConvoyPOICreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ConvoyPOIIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ConvoyPOI update
 */
export type ConvoyPOIUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ConvoyPOI
   */
  select?: Prisma.ConvoyPOISelect<ExtArgs> | null
  /**
   * Omit specific fields from the ConvoyPOI
   */
  omit?: Prisma.ConvoyPOIOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ConvoyPOIInclude<ExtArgs> | null
  /**
   * The data needed to update a ConvoyPOI.
   */
  data: Prisma.XOR<Prisma.ConvoyPOIUpdateInput, Prisma.ConvoyPOIUncheckedUpdateInput>
  /**
   * Choose, which ConvoyPOI to update.
   */
  where: Prisma.ConvoyPOIWhereUniqueInput
}

/**
 * ConvoyPOI updateMany
 */
export type ConvoyPOIUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ConvoyPOIS.
   */
  data: Prisma.XOR<Prisma.ConvoyPOIUpdateManyMutationInput, Prisma.ConvoyPOIUncheckedUpdateManyInput>
  /**
   * Filter which ConvoyPOIS to update
   */
  where?: Prisma.ConvoyPOIWhereInput
  /**
   * Limit how many ConvoyPOIS to update.
   */
  limit?: number
}

/**
 * ConvoyPOI updateManyAndReturn
 */
export type ConvoyPOIUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ConvoyPOI
   */
  select?: Prisma.ConvoyPOISelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ConvoyPOI
   */
  omit?: Prisma.ConvoyPOIOmit<ExtArgs> | null
  /**
   * The data used to update ConvoyPOIS.
   */
  data: Prisma.XOR<Prisma.ConvoyPOIUpdateManyMutationInput, Prisma.ConvoyPOIUncheckedUpdateManyInput>
  /**
   * Filter which ConvoyPOIS to update
   */
  where?: Prisma.ConvoyPOIWhereInput
  /**
   * Limit how many ConvoyPOIS to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ConvoyPOIIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ConvoyPOI upsert
 */
export type ConvoyPOIUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ConvoyPOI
   */
  select?: Prisma.ConvoyPOISelect<ExtArgs> | null
  /**
   * Omit specific fields from the ConvoyPOI
   */
  omit?: Prisma.ConvoyPOIOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ConvoyPOIInclude<ExtArgs> | null
  /**
   * The filter to search for the ConvoyPOI to update in case it exists.
   */
  where: Prisma.ConvoyPOIWhereUniqueInput
  /**
   * In case the ConvoyPOI found by the `where` argument doesn't exist, create a new ConvoyPOI with this data.
   */
  create: Prisma.XOR<Prisma.ConvoyPOICreateInput, Prisma.ConvoyPOIUncheckedCreateInput>
  /**
   * In case the ConvoyPOI was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ConvoyPOIUpdateInput, Prisma.ConvoyPOIUncheckedUpdateInput>
}

/**
 * ConvoyPOI delete
 */
export type ConvoyPOIDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ConvoyPOI
   */
  select?: Prisma.ConvoyPOISelect<ExtArgs> | null
  /**
   * Omit specific fields from the ConvoyPOI
   */
  omit?: Prisma.ConvoyPOIOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ConvoyPOIInclude<ExtArgs> | null
  /**
   * Filter which ConvoyPOI to delete.
   */
  where: Prisma.ConvoyPOIWhereUniqueInput
}

/**
 * ConvoyPOI deleteMany
 */
export type ConvoyPOIDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ConvoyPOIS to delete
   */
  where?: Prisma.ConvoyPOIWhereInput
  /**
   * Limit how many ConvoyPOIS to delete.
   */
  limit?: number
}

/**
 * ConvoyPOI without action
 */
export type ConvoyPOIDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ConvoyPOI
   */
  select?: Prisma.ConvoyPOISelect<ExtArgs> | null
  /**
   * Omit specific fields from the ConvoyPOI
   */
  omit?: Prisma.ConvoyPOIOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ConvoyPOIInclude<ExtArgs> | null
}
